### ISSUE TITLE
Close Eclipse console when associated language server is stopped

### ISSUE THREAD

**Issue by jubax** [eclipse/wildwebdeveloper#390] opened 2020-03-23 15:18 UTC
When opening .html/.less files in Eclipse the console shows multiple non-closeable "Angular Language Server" consoles.

See the corresponding Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=544082

This was one of the first things I noted after upgrading to Eclipse 4.15. The new generic text editor looks very nice, but the consoles should not show up. 

Maybe just log into the regular Eclipse error log?

**Comment by mickaelistria** [comment] 2020-03-23 15:31
I think it's also related to https://github.com/angular/vscode-ng-language-service/pull/584 . Basically, the Angular language server is too verbose, there is usually no point in showing this console to end-users, it's more interesting to developers.

**Comment by PAX523** [comment] 2020-08-14 11:10
When will this be fixed in Eclipse? I hoped that with the previous latest Eclipse release it was fixed? It's really nerve-racking!

**Comment by mickaelistria** [comment] 2020-08-16 21:53
@PAX523 A pull request or concrete hints to help fixing that would be welcome. For example, if you know how the Angular LS can be made less verbose, that'd be useful.

**Comment by PAX523** [comment] 2020-08-17 05:44
If you don't need Angular Language Server you could possibly disable it under: Window -> Preferences -> Language Servers

Uncheck "TypeScript - Angular Language Server" and "HTML - Angular Language Server".

**Comment by jubax** [comment] 2020-08-17 06:10
> @PAX523 A pull request or concrete hints to help fixing that would be welcome. For example, if you know how the Angular LS can be made less verbose, that'd be useful.

I just wanted to note that IMO the language server console should not be shown at all. I mean, the syntax analysis of other languages (e.g. Java) also does not log on the console; only errors to the error log if needed.

**Comment by mickaelistria** [comment] 2020-09-11 20:06
Closed as a duplicate of #438 . The goal isn't to auto-close the console, but to not have uninteresting messages shown at all.

**Closed by mickaelistria** 2020-09-11 20:06 UTC
