### ISSUE TITLE
Javascript editor only shows option to fix the first ESLint error

### ISSUE THREAD

**Issue by wesleybl** [eclipse/wildwebdeveloper#1122] opened 2023-03-09 13:14 UTC
When we move the mouse over a line with an ESLint error, only is shown the option to fix the error, if it is the first line with an error. In subsequent lines, the option is not shown. See:

[Gravação de tela de 09-03-2023 10:03:52.webm](https://user-images.githubusercontent.com/3297795/224032638-0a33b758-96fa-45e9-9d20-acc10029d49f.webm)

In the video it doesn't show the cursor, but the first popup appeared when I hovered the mouse over the first line, and the second when I hovered over the second line.

In the log, I see the error:

```
!ENTRY org.eclipse.lsp4e 4 0 2023-03-09 09:54:37.959
!MESSAGE org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request textDocument/codeAction failed with message: Invalid regular expression: //** eslint-disable-next-line/: Nothing to repeat
!STACK 0
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request textDocument/codeAction failed with message: Invalid regular expression: //** eslint-disable-next-line/: Nothing to repeat
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.eclipse.lsp4e.operations.codeactions.LSPCodeActionMarkerResolution.checkMarkerResoultion(LSPCodeActionMarkerResolution.java:168)
	at org.eclipse.lsp4e.operations.codeactions.LSPCodeActionMarkerResolution.getResolutions(LSPCodeActionMarkerResolution.java:102)
	at org.eclipse.ui.internal.ide.registry.MarkerHelpRegistry.getResolutions(MarkerHelpRegistry.java:394)
	at org.eclipse.ui.internal.genericeditor.markers.MarkerInformationControl.setInput(MarkerInformationControl.java:107)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeInformationControl.setInput(CompositeInformationControl.java:75)
	at org.eclipse.jface.text.AbstractInformationControlManager.internalShowInformationControl(AbstractInformationControlManager.java:1151)
	at org.eclipse.jface.text.AbstractInformationControlManager.presentInformation(AbstractInformationControlManager.java:1120)
	at org.eclipse.jface.text.AbstractHoverInformationControlManager.presentInformation(AbstractHoverInformationControlManager.java:884)
	at org.eclipse.jface.text.TextViewerHoverManager.doPresentInformation(TextViewerHoverManager.java:237)
	at org.eclipse.jface.text.TextViewerHoverManager.lambda$3(TextViewerHoverManager.java:227)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request textDocument/codeAction failed with message: Invalid regular expression: //** eslint-disable-next-line/: Nothing to repeat
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$3(LanguageServerWrapper.java:287)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

This error is occurring in version 1.0.2. In previous versions, the option was shown on all lines with an error.

**Comment by mickaelistria** [comment] 2023-03-14 12:23
Can you please try latest release or latest snapshots and report whether you can reproduce this issue or not?

**Comment by wesleybl** [comment] 2023-03-14 13:46
@mickaelistria in 1.0.3 the error also occurs. But actually, you need to have `eslint` configured with `prettier`. 

I created this repository with this configured:

https://github.com/wesleybl/test-eslint

You can run `npm install` on it and create an Eclipse project in its folder.

**Comment by mickaelistria** [comment] 2023-03-14 13:49
I suspect the issue comes from the vscode-eslint language server; the behavior is really language specific and the response message shows an internal error in the language server. Can you please report it to https://github.com/Microsoft/vscode-eslint ?

**Comment by mickaelistria** [comment] 2023-03-14 14:10
> Do you know how to configure vscode to display these errors?

Sorry, no.

**Comment by wesleybl** [comment] 2023-03-14 16:07
@mickaelistria I was able to make the suggested eslint errors fixes appear in vscode by installing the `ESLint` plugin. I have `ESLint` 2.4.0 plugin and vscode 1.76.1. With these versions everything works fine in vscode. So I'm not sure if this is a problem of the `vscode-eslint`.

It seems that version 2.3.3 of the `vscode-eslint` is used here:

https://github.com/eclipse/wildwebdeveloper/blob/762cf039ad5226c9dbc431cf3d918a8ee054adb0/org.eclipse.wildwebdeveloper/pom.xml#L42-L45

Could you please update to version 2.4.0, to see if the issue is fixed?

**Comment by mickaelistria** [comment] 2023-03-14 16:31
Would you be willing to submit the pull request?

**Comment by wesleybl** [comment] 2023-03-14 19:04
> Would you be willing to submit the pull request?

I can try when I have free time. But how do I start an instance of Eclipse, using the master branch code? I tried taking a look at:

https://github.com/eclipse/wildwebdeveloper/blob/master/CONTRIBUTING.md

But that wasn't clear to me.

**Comment by mickaelistria** [comment] 2023-03-14 19:50
https://github.com/eclipse/wildwebdeveloper/blob/master/CONTRIBUTING.md#%EF%B8%8F-setting-up-the-development-environment-manually is supposed to describe it. If you have specific questions, I'll happily try to answer them in this document.

**Comment by wesleybl** [comment] 2023-03-15 19:13
@mickaelistria one thing I found strange is that the documentation asks to install the snapshot:

> Install latest Wild Web Developer snapshot in your target-platform (can be your current IDE) as described above

However, I've just cloned master, and would like to use master's code. Is installing the snapshot a prerequisite for using the master code?

How do I run an instance of Eclipse, using the master code? I must go to `Run -> Run Configurations... -> Eclipse Application` ?

**Comment by mickaelistria** [comment] 2023-03-16 01:09
> However, I've just cloned master, and would like to use master's code. Is installing the snapshot a prerequisite for using the master code?

No, but it usually makes things easier.

> How do I run an instance of Eclipse, using the master code? I must go to Run -> Run Configurations... -> Eclipse Application ?

Exactly.

**Comment by wesleybl** [comment] 2023-03-16 15:00
> I don't think so; if you've installed snapshots, it's actually the build from master.

That's precisely why I'm asking if the problem is in the master. In release 1.0.3, ESLint errors are shown.

> I can't tell but I don't think it is. I suspect that the ESLint language server is simply not started in your test. You can check it by looking at the subprocesses of the runtime IDE.

I think the server has started, because in the log it shows:

```
!ENTRY org.eclipse.lsp4e 1 0 2023-03-16 11:58:02.258
!MESSAGE [Info]	ESLint server running in node v18.13.0
```

**Comment by vrubezhny** [comment] 2023-03-16 18:49
> Could you please update to version 2.4.0, to see if the issue is fixed?

@wesleybl When checking the code changes for vscode-eslint between `pre-release//2.3.3` and the current `release//2.4.0`  I cannot spot any change that is related to ESLint Language server - that's the reason we're not updated yet to this version.

For me ES Lint shows the errors in JavaScript files,  but not those you are expecting to see with your example.

Also, I'm not an expert in Prettier, but it looks like ES Lint has nothing to do with it... Prettier is an independent code formatter, not a part of ES Lint validation.

I expect ES Lint itself can have some preferences that make the validation more or less less strict in some areas - if you can find such preferences we can think of using it in ES Lint LS configuration or making it configurable option in WWD.

**Comment by wesleybl** [comment] 2023-03-16 20:25
> For me ES Lint shows the errors in JavaScript files, but not those you are expecting to see with your example.

@vrubezhny  for me, errors are also shown. See in the video that the two lines are marked in red. But the option to fix the error (Fix all auto-fixable problems), when leaving the mouse on the line with error, only appears on the first line with error.

> Also, I'm not an expert in Prettier, but it looks like ES Lint has nothing to do with it... Prettier is an independent code formatter, not a part of ES Lint validation.

Yes it is another formatter. But we have an ESLint plugin, to show Prettier errors. To see:

https://github.com/wesleybl/test-eslint/blob/master/.eslintrc.js#L17

But in Eclipse 2023-03, we can't even see this issue anymore, because of #1133

**Comment by wesleybl** [comment] 2023-03-17 13:07
For registration:

While this issue is not resolved, I used the URL:

https://download.eclipse.org/wildwebdeveloper/releases/1.0.1/

to install version `1.0.1`. In this version, this problem does not happen.

**Comment by vrubezhny** [comment] 2023-03-17 20:49
WWD 1.0.1 embeds eslint-server v. 2.2.5. Some VSCode users also downgrading the vscode-eslint due to the similar reasons.
The strange thing here is that when I was merging the PR https://github.com/eclipse/wildwebdeveloper/pull/1128 it was built with success including the `TestESLint.testESLintDiagnostics` JUnit test - at that point we have already had  `vscode-eslint pre-release//2.3.3` merged in. So it looks like the problem has started to happen because of some 3rd plugin or an NPM dependency was updated lately.

**Comment by wesleybl** [comment] 2023-03-17 21:08
> The strange thing here is that when I was merging the PR https://github.com/eclipse/wildwebdeveloper/pull/1128 it was built with success including the TestESLint.testESLintDiagnostics JUnit test - at that point we have already had vscode-eslint pre-release//2.3.3 merged in.

`TestESLint.testESLintDiagnostics` test failure is related to: #1133. Not with this one.

The test started to fail after Eclipse 2023-03 was released. So probably PR https://github.com/eclipse/wildwebdeveloper/pull/1128 was run with Eclipse 2022-12. That's why he passed.

**Comment by vrubezhny** [comment] 2023-03-18 12:05
The reason of not working ESLint LS is LSP4E updated to v.0.22.0, the workaround could be downgrading LSP4E to [v.0.21.0](https://download.eclipse.org/lsp4e/releases/0.21.0/) until the issue is fixed in LSP4E.

**Comment by mickaelistria** [comment] 2023-03-18 20:18
Source issue is https://github.com/eclipse/lsp4e/issues/560 .

**Comment by mickaelistria** [comment] 2023-03-22 13:23
Thanks for linking!

**Comment by wesleybl** [comment] 2023-03-22 14:26
@mickaelistria how do I see eslint server log in Eclipse?

**Comment by mickaelistria** [comment] 2023-03-22 14:33
>  how do I see eslint server log in Eclipse?

You can access the LSP-level logs, but AFAIK other logs are not available. You'd need to tweak ESLintLanguageServer class so it sets the right options to capture the log; unless this is available by default when starting the server?

**Comment by wesleybl** [comment] 2023-03-22 14:50
>  You'd need to tweak ESLintLanguageServer class so it sets the right options to capture the log; unless this is available by default when starting the server?

I can see the logs, without making any changes. Thanks!

**Comment by wesleybl** [comment] 2023-04-13 00:30
Does anyone know how to simulate hovering in the test in order to capture code actions (like Fix all auto-fixable problems) when we hover over a line with eslint errors?

I tried to do it with:

https://github.com/eclipse/wildwebdeveloper/blob/1ed945dde0501136c5be7e2aabd65c908afd39c5/org.eclipse.wildwebdeveloper.tests/src/org/eclipse/wildwebdeveloper/tests/TestTypeScript.java#L54-L69

but that doesn't capture the suggestions that eslint makes when I hover over a line with errors.

**Comment by vrubezhny** [comment] 2023-04-13 01:44
@wesleybl I don't think the hover you're getting with this test contains any code actions added...

Not sure if it helps, but did you try searching for markers in the file and then tying to get the marker resolutions?..
```
IMarker[] markers = file.findMarkers("org.eclipse.lsp4e.diagnostic", true, IResource.DEPTH_ZERO);
if (markers.length > 0 l) {
	for (IMarker m : markers) {
		System.out.println("M: " + m.getAttribute(IMarker.MESSAGE) + ". " + m.toString());
	}
	IMarkerResolution[] markerResolutions = IDE.getMarkerHelpRegistry().getResolutions(markers[0]);
	// Test Marker Resolutions...
	for (IMarkerResolution mr : markerResolutions) {
		System.out.println("MR: " + mr.getLabel() + ". " + mr.toString());
	}
}
```
For me with the test you've mentioned (unless you've modified the content of the test file)  this code finds one error marker on 'html' (`Cannot find name 'html'.`), but not any resolutions.  Not more.

**Comment by wesleybl** [comment] 2023-04-14 12:43
> I don't think the hover you're getting with this test contains any code actions added...

@vrubezhny  I thought I would have to simulate the hover, since for the suggestions to appear, we have to hover.

> Not sure if it helps, but did you try searching for markers in the file and then tying to get the marker resolutions?..

That worked, thanks! I didn't know suggestions were called resolutions. I actually don't understand anything about lsp4e. I'm not even a Java developer :smile: .

> For me with the test you've mentioned (unless you've modified the content of the test file) this code finds one error marker on 'html' (Cannot find name 'html'.), but not any resolutions.

I used that test as a base, but I did change it.

With your tips, I'll try to do a test for this issue.

**Comment by vrubezhny** [comment] 2023-05-15 09:27
@wesleybl The issue looks to be fixed in just released  [vcode-eslint v.2.4.1](https://github.com/microsoft/vscode-eslint/releases/tag/pre-release%2F2.4.1) , So you try  updating to WWD 1.1.1 which includes the fixed version of vscode-eslint - not released yet, but you can try installing it from a snapshot - https://download.eclipse.org/wildwebdeveloper/snapshots/

Note that for correct work of Maven Editor the M2E-Core is to be updated to v.2.3.0 (also not released yet, can be installed from snapshot - https://download.eclipse.org/technology/m2e/snapshots/2.3.0/).

Feel free to reopen the issue if the problem still  persists after updating.

**Closed by vrubezhny** 2023-05-15 09:27 UTC

**Comment by wesleybl** [comment] 2023-05-29 19:05
@vrubezhny although https://github.com/microsoft/vscode-eslint/pull/1611 fixed this problem, I had noticed that the main problem was that wwd was not sending the `languageId` to the vscode-eslint. So `languageId` arrived empty here:

https://github.com/microsoft/vscode-eslint/blob/4ab4bb621d55931705431d4bda55d1a7c8f00e06/server/src/eslintServer.ts#L692

Do you know if this has been fixed, to avoid problems in the future?

**Comment by vrubezhny** [comment] 2023-05-29 23:00
> @vrubezhny although [microsoft/vscode-eslint#1611](https://github.com/microsoft/vscode-eslint/pull/1611) fixed this problem, I had noticed that the main problem was that wwd was not sending the `languageId` to the vscode-eslint. So `languageId` arrived empty here:

@wesleybl This should be  fixed with https://github.com/eclipse/wildwebdeveloper/commit/c3ba0fd1e8c98beaeeec93204145980a7b0bbe55
