### ISSUE TITLE
JavaScript scrambled

### ISSUE THREAD

**Issue by rvwilliams** [eclipse/wildwebdeveloper#213] opened 2019-08-05 13:57 UTC
I'm using wild web developer with Eclipse 2019-06 PHP IDE as my projects contain both JavaScript and PHP.  I use SVN for versioning.  If I open an existing JavaScript file with the generic editor and format it, a large number of typing-type errors are reported that aren't there when I use the built-in JavaScript editor.  This might be '(expected' when an open bracket is present.  Deleting it and re-typing removes the error.  However as there are so many similar errors reported, this just takes too much time so I've stopped using the Generic Editor.

**Comment by mickaelistria** [comment] 2019-08-05 13:58
Can you please share an example file and some precise steps to reproduce the issue?

**Comment by rvwilliams** [comment] 2019-08-05 14:07
Here's an example
`function addToLines(lineNumber, code, x1, y1, x2, y2, length, type, parallelTo) {
	lines[lineNumber] = {
		'no': lineNumber,
		'code': code,
		'x1': x1,
		'y1': y1,
		'x2' x2,
		'y2': y2,
		'length': length,
		'type': type,
		'parallelTo': parallelTo
	};
	console.log(lines);
	return;


}`
The Generic Text Editor has lost the : on line 7 between 'x2' and x2

**Comment by rvwilliams** [comment] 2019-08-05 14:21
I have files created with the JavaScript editor when Wild Web Developer wasn't installed.  These had no typing etc. errors.  I installed Wild Web developer and opened some of these files using the Generic Editor.  After formatting (CTRL-SHFT-F) a large number of red errors appeared.  Inspecting these I found various charfacters had been dropped, such as the : in the above example,  Another example is the ')' on a function statement that has no parameters.

**Comment by mickaelistria** [comment] 2019-08-06 15:56
Do I get it right that the issue is only on Format?
Can you please share an example of the *initial* file (before formatting)? In the example you gave earlier, the `:` is already missing? Don't be afraid of giving more details about the steps to reproduce: initial file, what specific action you run...

**Comment by mickaelistria** [comment] 2020-03-13 04:31
No answer for 9 months, closing.
Please consider trying latest release, with a proper JS file and reopen with more details if there is still an issue.

**Closed by mickaelistria** 2020-03-13 04:31 UTC
Labels: bug
