### ISSUE TITLE
Unable to indent blocks of code

### ISSUE THREAD

**Issue by 4javier** [eclipse/wildwebdeveloper#357] opened 2020-02-16 14:05 UTC
I'm experiencing the same behaviour reported in this old ticket
https://github.com/eclipse/wildwebdeveloper/issues/131

With Generic Text Editor I cannot indent a whole selected block of codelines. 
I can do that with HTML Editor. 

Is it a regression, or I'm the only one?

> Spring Tool Suite 4
> Version: 4.5.1.RELEASE
> Build Id: 202001211336

Another thing I don't understand is why, even if I installed the plugin by Eclipse Marketplace at version 0.8.1, my installation details report this:

> org.eclipse.wildwebdeveloper (0.5.3.202001151110) "Wild Web Developer: web development in Eclipse IDE" [Active]
> org.eclipse.wildwebdeveloper.xml (0.6.0.202001131219) "XML support using Language Server" [Starting]

**Comment by jabby** [comment] 2020-02-17 14:38
I tried WWD in a plain old Java Eclipse packaging and it works. But as you experiencing, it does not work in STS4. I will continue to investigate on this.

**Comment by jabby** [comment] 2020-02-17 15:27
First try, I defined Generic Editor as default editor for *.html and *.htm files. It does not help.

Second try, I uninstalled the following features: 

* Eclipse JSON Editor and Tools
* Eclipse Web Developer Tools
* Eclipse XML Editors and Tools
* m2e-wtp - JAX-RS configurator for WTP (Optional)
* m2e-wtp - JSF configurator for WTP (Optional)
* m2e-wtp - Maven Integration for WTP
* WST Server Adapters
* WST Server UI

Then indentation for block works when using Generic Editor for *.html files

Thrid try. Reset uninstall then remove from plugins folder the following plugins: 

* org.eclipse.wst.html.core_1.3.200.v201910140306.jar
* org.eclipse.wst.html.ui_1.1.200.v201905301652.jar

Indentation works again. I think the problem comes from incompatibility between WTP html editor and WWD. It's not a good solution but a workaround if you don't need html support in JSP.  

@4javier I will continue to investigate how to solve your problem.

**Comment by 4javier** [comment] 2020-02-17 18:32
Thanks for your efforts.
I did already tried to set WWD Generic Editor as defaults, but that didn't help for me neither.
I'd rather not to touch default STS installation to avoid future problems, even if I'm working just with Java and Angular. 
Let me know if you got any news, or need other info.

**Comment by akurtakov** [comment] 2020-02-17 18:36
Please report this to STS. They should stop shipping wtp editors in favor of wwd IMHO.

**Comment by angelozerr** [comment] 2020-02-17 18:38
Have you some errors in the log view when the indent problem occurs ?

**Comment by 4javier** [comment] 2020-02-17 18:48
@angelozerr 
No new lines in error log when I try to block indent. I would even uninstall WTP, but I suspect it's dependency for WWD.
@akurtakov 
I'll notify them the problem and link this thicket.

**Comment by akurtakov** [comment] 2020-02-17 19:05
> @angelozerr
> No new lines in error log when I try to block indent. I would even uninstall WTP, but I suspect it's dependency for WWD.

WWD has no dependency on WTP so unless you need jsp/jsf it should be safe to uninstall wtp.

> @akurtakov
> I'll notify them the problem and link this ticket.

**Comment by 4javier** [comment] 2020-02-17 19:10
This is a shot form marketplace, choosing to change WTP installation. WWD is listed inside it, and three other components are marked as required.

![Schermata da 2020-02-17 20-08-06](https://user-images.githubusercontent.com/459381/74680650-91826000-51c1-11ea-953e-f821f81a0d9d.png)

**Comment by jabby** [comment] 2020-02-17 19:15
> 
> 
> Please report this to STS. They should stop shipping wtp editors in favor of wwd IMHO.

I think it is quite difficult to remove WTP from STS4. 
If I understand correctly what WTP commiter said, JSP support need html / css / JS support from other part of WTP. So in case where STS4 want to support JSP editing, there is a dependency to WTP html support.

**Comment by akurtakov** [comment] 2020-02-17 19:18
WTP may depend on WWD but WWD has no dep on WTP is what I mean. It is really up to whether you need JSP/JSF or not. If not only WWD will probably give you better results.

**Comment by nitind** [comment] 2020-02-17 22:23
WTP's involvement with this is fixed in 2020-03M3.

**Comment by 4javier** [comment] 2020-02-18 10:39
@nitind 
I'm a bit confused about eclipse versioning.
Do you know when it will be adopted by STS?

**Comment by mickaelistria** [comment] 2020-02-18 13:16
Version of the bundle isn't so correlated with version of the project as Wild Web Developer tries to use semantic versioning for bundles vs «marketing» versioning for the project.
I thnk the version of the feature does match project version though.

Thanks a lot for everyone's feedbackand analysis. I'm then closing it as it's not a bug in.Wild Web Developer but in WTP.
Upgrading to WTP 2020-03 or removing WTP should fix the issue.

**Closed by mickaelistria** 2020-02-18 13:16 UTC

**Comment by martinlippert** [comment] 2020-02-19 08:50
> Please report this to STS. They should stop shipping wtp editors in favor of wwd IMHO.

@akurtakov I absolutely agree, but sadly this is not as straight forward as it seems (due to various dependencies) and additional work on our side to re-integrate our extensions for WTP into WWD. So yes, the goal is clear, but it involves a bit more work than just including the other features.

In addition to that switching completely from WTP to WWD is quite a big step for our users that needs to be planned and executed very carefully (with regards to removing existing features, replacing functionality, etc.).

Again, not an argument against switching to WWD (absolutely the right way to go), but the reason why we haven't taken that step yet.

**Comment by martinlippert** [comment] 2020-02-19 08:53
> @nitind
> I'm a bit confused about eclipse versioning.
> Do you know when it will be adopted by STS?

@4javier Spring Tools 4 for Eclipse will ship on top of Eclipse 2020-03 as soon as that Eclipse version is shipped, usually with a one-day delay. So you could expect Spring Tools 4 for Eclipse 4.6.0 (based on Eclipse 2020-03) to be released in late March. Hope that helps.

In the meantime, you could always try a CI build of Spring Tools 4 for Eclipse from here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html. It usually contains the latest bits that got published for Eclipse 2020-03, so as soon as M3 of that Eclipse version is out the door, you should see it being included in our nightly builds - if you want to give it a try.
