### ISSUE TITLE
Angular Language Server popup error

### ISSUE THREAD

**Issue by vincenzocaselli** [eclipse/wildwebdeveloper#836] opened 2022-06-16 10:03 UTC
Recently, every time I open a file with  Generic Text editor (e.g. .ts and .html files), I keep getting the following popup error

![Screenshot_20220613_183624](https://user-images.githubusercontent.com/3648713/174042996-2091d895-3484-4ad8-9d6a-a7a0a308448a.png)

I tried to follow the instructions suggested:

**Trial#1 (npm)**
`npm run ngcc`
> npm ERR! missing script: ngcc
> npm ERR!
> npm ERR! Did you mean this?
> npm ERR!     ng

**Trial#2 (yarn)**
`yarn run ngcc`
> error Command "ngcc" not found. Did you mean "ngc"?

The problem happens both with **2022-03** and **2022-06** Eclipse releases.

Other details that may help:
- Angular CLI version (7.2.4) 
- npm 6.14.17
- Wild Web Developer 0.10.14.202205271506

What should I do in order to avoid this popup?

Thank you very much

**Comment by akurtakov** [comment] 2022-06-16 11:08
This is hopefully fixed via https://github.com/eclipse/wildwebdeveloper/commit/8c834d725dc9260106b86fa947d5f91919c73e33 . Can you try with https://download.eclipse.org/wildwebdeveloper/snapshots/ whether it's fixed for you?

**Comment by vincenzocaselli** [comment] 2022-06-16 14:01
I double checked here
![image](https://user-images.githubusercontent.com/3648713/174086896-6f7695a7-e69b-4981-af96-2ee69e6c4714.png)
(already restarted Eclipse twice after installation)

**Comment by vincenzocaselli** [comment] 2022-06-17 10:01
In addition, a click on the button **Show Output** just closes the dialog, but doesn't show anything 
(this was happening also before installing from the snapshot update site)

**Comment by akurtakov** [comment] 2022-06-17 10:02
@vrubezhny Looks like your expertise is needed here.

**Comment by mickaelistria** [comment] 2022-06-18 16:40
Do you reproduce this issue with a more recent Angular project? I don't think Angular Language Server still supports v7.

**Comment by vincenzocaselli** [comment] 2022-06-20 10:04
Unfortunately, due to customer constraints we have to stick to Angular 7

**Comment by vincenzocaselli** [comment] 2022-08-22 10:24
Apart from the error, which popups indeed very frequently,  the WWD seems to work even with Angular 7.
Is there a way to disable this popup (some hack would be fine too)?

**Comment by mickaelistria** [comment] 2022-08-23 14:25
Can you please share a minimal project to reproduce this issue? I don't have a fresh Angular project at hand to reproduce it. But really we cannot do better than what the LS supports.
You could write a dedicated plugin for this; that would listen to active shell change and automatically close this pop-up when it appears...

**Comment by vincenzocaselli** [comment] 2022-09-29 22:54
Yes, here is a minimal project.

1. unzip it
2. open a terminal on root folder and type
`npm install`
3. import as an Eclipse project
4. open 
  > src/app/app.component.ts

  and wait a few seconds: the popup shows up

[wwd-ng7.zip](https://github.com/eclipse/wildwebdeveloper/files/9679488/wwd-ng7.zip)

**Comment by lorenzodallavecchia** [comment] 2022-12-11 14:45
I encountered this problem recently with Angular 13 and did some investigation.

First, I suggest enabling Angular Language Server _file_ logging and then opening `<workspace>/.metadata/angular-language-server.log`. This file is not the same I/O log but the actual internal log of Angular.
In the log, I found the reason behind the error message.

```
Err 27    [15:16:30.192] Failed to run ngcc for d:/work/myworkspace/myproject/tsconfig.json, language service may not operate correctly:
    Failed to resolve ngcc from d:/work/myworkspace/myproject
```

I looked for the error message in Angular sources. To summarize, Angular is doing the following:

- It detects that I am using `@angular/core` as a library (it is not inside TypeScript sources, which is correct since it is in node_modules).
- It detects that I am using Ivy (also correct, I don't have `"useIvy": false` in `tsconfig.json`).
- With such configuration, it attempts to run the `ngcc` program before starting server operation. It does so to ensure that external libraries (including `@angular/core`) have Ivy-compatible metadata.
- In my case it cannot resolve the package that contains `ngcc`, which is `@angular/compiler-cli`.

The problem in my case was that I did not have `@angular/compiler-cli` installed (I'm not using the `ng` CLI, so no surprise). After installing it, the problem disappeared.

I guess the problem started after an update of the Angular service included in WWWD or maybe after WWWD began to handle the "display popup window" request from Angular.
Unfortunately, it isn't possible to disable the message because this is an internal behavior of Angular.

@vincenzocaselli I tried your repro. The problem in your case is that `@angular/compiler-cli` is present but does not contain the `ngcc` program, as it was introduced in Angular 8. Maybe you could add a fake ngcc file to trick Angular into thinking that it run the real thing.

It would be nice if WWWD allowed using installed Node packages instead of its built-in ones. Unfortunately, this limitation is also true for TypeScript: if you use an older TS, the editors will allow using new features you can not compile later.

**Comment by vrubezhny** [comment] 2023-01-19 18:29
Automatic NGCC check can be disabled for an Angular project. 
@angelozerr Could you, please, review #1061?

**Closed** 2023-01-24 14:12 UTC
