### ISSUE TITLE
No syntax highlighting on json, js, ts, less, css, yml

### ISSUE THREAD

**Issue by Amenel** [eclipse/wildwebdeveloper#587] opened 2020-12-30 12:00 UTC
I have installed Wild Web Developer via the update site at http://download.eclipse.org/wildwebdeveloper/snapshots

Curiously, the release notes file talks about a 0.11.5 tentative release date in 2021, but the version Eclipse shows in my installation is 0.10.5.202012011111 (note 0.**10** and not 0.11). The version timestamp (20201201) matches the date mentioned in the release notes for 0.11.4, but the 'Schema Associations' preference page, mentioned in 0.11.4 is not present in my Eclipse instance. I'm quite confused.

My problem is that even though files are opened with the Generic Editor, I have no syntax highlighting in files other than XML, i.e. json, js, ts, less, css and yml.

I've looked at the list of language servers in the preferences, here it is:

![2020-12-30 12_36_09-Preferences](https://user-images.githubusercontent.com/7868710/103349259-aa73c700-4a9c-11eb-8654-f1d35fda30b7.png)

Is the list complete? Shouldn't there also be additional language servers, for instance to handle JSON?

It looks like the plugin does not kick in to handle JSON/JS/TS, LESS/CSS and YAML. At the moment, it seems to me that only XML files benefit from the rich edition.

I haven't received any error notifications and the error log is empty with respect to this issue. I don't see any relevant Console to display.

I'm wondering if there's anything to do other than installing the plugin and restarting Eclipse that I haven't done?

**Comment by mickaelistria** [comment] 2021-01-04 14:42
Can you please verify that the `org.eclipse.wildwebdeveloper` plugin is properly installed and running in your IDE (via Help > About > Installation Details > Plugins)? It looks like only the XML support was installed.

**Comment by mickaelistria** [comment] 2021-02-18 16:36
No feedback for more than a month, and this couldn't be reproduced and looks like Wild Web Developer was not properly installed by user. I assume we can close it.

**Closed by mickaelistria** 2021-02-18 16:36 UTC
