### ISSUE TITLE
InvalidPathException on start

### ISSUE THREAD

**Issue by mauromol** [eclipse/wildwebdeveloper#366] opened 2020-02-24 13:28 UTC
I recently upgraded to Eclipse 2019-12 and tried to install Wild Web Developer plugin.

On Eclipse start today I got this, I don't know if it happens always, but today I saw this because the Error Log view was open:

```
eclipse.buildId=4.14.0.I20191210-0610
java.version=1.8.0_202
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/D:/ws/rolling/DCS-SHOP-trunk/

org.eclipse.ui.workbench
Error
Mon Feb 24 13:02:46 CET 2020
Plug-in "org.eclipse.wildwebdeveloper.xml" was unable to instantiate class "org.eclipse.wildwebdeveloper.xml.XMLLanguageServer".

org.eclipse.core.runtime.CoreException: Plug-in "org.eclipse.wildwebdeveloper.xml" was unable to instantiate class "org.eclipse.wildwebdeveloper.xml.XMLLanguageServer".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:206)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:929)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:118)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:210)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:652)
	at org.eclipse.lsp4e.LanguageServiceAccessor.lambda$14(LanguageServiceAccessor.java:589)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:602)
	at org.eclipse.lsp4e.operations.color.DocumentColorProvider.provideCodeMinings(DocumentColorProvider.java:60)
	at org.eclipse.lsp4e.operations.color.DocumentColorProvider.provideCodeMinings(DocumentColorProvider.java:87)
	at org.eclipse.jface.internal.text.codemining.CodeMiningManager.lambda$2(CodeMiningManager.java:189)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.eclipse.jface.internal.text.codemining.CodeMiningManager.getCodeMinings(CodeMiningManager.java:195)
	at org.eclipse.jface.internal.text.codemining.CodeMiningManager.updateCodeMinings(CodeMiningManager.java:140)
	at org.eclipse.jface.internal.text.codemining.CodeMiningManager.run(CodeMiningManager.java:129)
	at org.eclipse.jface.text.source.SourceViewer.updateCodeMinings(SourceViewer.java:1313)
	at org.springframework.tooling.ls.eclipse.commons.STS4LanguageClientImpl.lambda$8(STS4LanguageClientImpl.java:383)
	at org.springframework.tooling.jdt.ls.commons.classpath.ReusableClasspathListenerHandler$CallbackJob.lambda$0(ReusableClasspathListenerHandler.java:77)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.tooling.jdt.ls.commons.classpath.ReusableClasspathListenerHandler$CallbackJob.run(ReusableClasspathListenerHandler.java:77)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor53.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:204)
	... 35 more
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files (x86)\GnuWin32\bin"
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.eclipse.wildwebdeveloper.xml.XMLLanguageServer.lambda$2(XMLLanguageServer.java)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at org.eclipse.wildwebdeveloper.xml.XMLLanguageServer.computeJavaPath(XMLLanguageServer.java:71)
	at org.eclipse.wildwebdeveloper.xml.XMLLanguageServer.<init>(XMLLanguageServer.java:37)
	... 39 more
```

I don't know why native GnuWin32 should be needed and where its path is taken from, but I suspect there's something wrong when handling paths with spaces.

**Comment by mauromol** [comment] 2020-02-27 15:42
Indeed this error appears repeatedly dozen times in my log file, polluting it. I had to temporarily uninstall WWD plugin until a solution is suggested.

**Comment by mickaelistria** [comment] 2020-02-27 15:54
It looks like you're using an older version of Wild Web Developer as the line numbers don't match actual code. Please first upgrade to newer release of Wild Web Developer.
But I think there is an actual bug here, although as a Linux user I cannot reproduce it. The fix can consist in reworking the chain which is not on line 118 so that it would "consume" the `"` or by finding the current java executable running the IDE and using this one.

**Comment by mauromol** [comment] 2020-02-27 15:56
I'm using WWD from the 2019-12 update site, doing a "check for updates" doesn't find anything new. Should I use some other update site?

**Comment by mickaelistria** [comment] 2020-02-27 16:00
what's the version of org.eclipse.wildwebdeveloper.xml bundle? Anyway, it won't fix the issue.

**Comment by mauromol** [comment] 2020-02-27 16:24
Now I've uninstalled it, but I previously had installed the version on 2019-12 update site, so the bundle is "Wild Web Developer - Developer and debug Web and Node applications" version 0.7.2.201911151547.

**Comment by mickaelistria** [comment] 2020-02-27 17:32
I submitted https://github.com/eclipse/wildwebdeveloper/pull/369 . I'll merge if tests succeed, then I'll ping you to try the snapshot build and report whether this works for you.

**Comment by mauromol** [comment] 2020-02-28 07:54
Ok, let me know.
Anyway, I'm just curious to know where this path comes wrong and why WWD would want to know where GnuWin32 is installed...

**Comment by mickaelistria** [comment] 2020-02-28 17:28
Please try snapshots from download.eclipse.org/wildwebdeveloper/snapshots and tell us whether it's fixed or not.

**Comment by mauromol** [comment] 2020-02-28 17:54
Can this be installed on 2019-12? Or do I need to try a 2020-03 snapshot?
Because on 2019-12 I get the following error:

```
An error occurred while collecting items to be installed
session context was:(profile=SDKProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.lsp4j,0.9.0.v20200130-1210
No repository found containing: osgi.bundle,org.eclipse.lsp4j.jsonrpc,0.9.0.v20200130-1210
No repository found containing: osgi.bundle,org.eclipse.lsp4e.debug,0.12.0.202001301838
No repository found containing: osgi.bundle,org.eclipse.lsp4j.debug,0.9.0.v20200130-1210
No repository found containing: osgi.bundle,org.eclipse.lsp4j.jsonrpc.debug,0.9.0.v20200130-1210
```

**Comment by mickaelistria** [comment] 2020-03-02 08:28
Can you please retry https://download.eclipse.org/wildwebdeveloper/snapshots ? I modified the repo a bit to hopefully avoid such issue.

**Comment by mauromol** [comment] 2020-03-02 09:29
Nope:

```
An error occurred while collecting items to be installed
session context was:(profile=SDKProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.lsp4j,0.9.0.v20200130-1210
No repository found containing: osgi.bundle,org.eclipse.lsp4j.jsonrpc,0.9.0.v20200130-1210
No repository found containing: osgi.bundle,org.eclipse.lsp4e.debug,0.12.0.202001301838
No repository found containing: osgi.bundle,org.eclipse.lsp4j.debug,0.9.0.v20200130-1210
No repository found containing: osgi.bundle,org.eclipse.lsp4j.jsonrpc.debug,0.9.0.v20200130-1210
```

**Comment by mickaelistria** [comment] 2020-03-02 09:32
Can you please go to Window > Preferences > Install/Update > Available software sites and remove the `*/lsp4e/snapshots` and `*/lsp4j/snapshots` sites and then try agian?

**Comment by mauromol** [comment] 2020-03-02 10:01
Ok, in this way I got it to be installed. I had the lsp4e snapshot update site enabled in my available software sites, I don't know where it came from (I never added it explicitly), but I know that sometimes there are unknown and obscure update sites appearing automatically in there (after many years of experience with Eclipse this is something I never understood completely...).

So, with this new snapshot version it seems like I get no more of the above exceptions in my log. Is there some action I can try to be sure that everything is working as expected?

**Comment by mickaelistria** [comment] 2020-03-02 10:03
> Is there some action I can try to be sure that everything is working as expected?

Nothing specific, just use it regalarly and you'll see ;)
The test suite are not so bad for Wild Web Developer so there aren't many regressions.

**Closed** 2020-03-03 07:30 UTC
