### ISSUE TITLE
CSS editor does not close bracket

### ISSUE THREAD

**Issue by vogella** [eclipse/wildwebdeveloper#156] opened 2019-03-26 16:43 UTC
The CSS support is very nice in wild web developer but the editor currently does not automatically close opening brackets.

Example: Create a new css file and add the following rule:

H1 { -> after typing the opening bracket I would expect that the closing bracket is created automatically.

**Comment by mickaelistria** [comment] 2019-03-26 18:22
Either the language-configuration for .css is not properly configured in Wild Web Developer, or it's correctly configured and TM4E doesn't properly take the given rules into account.
If bracket closing works for other languages, it's more likely the 1st one.

**Comment by mickaelistria** [comment] 2019-03-26 22:32
Bracket closing works for me. Can you please tell your version of Wild Web Developer and TM4E?
Also, can you please check in Preferences > TextMate > Language Configuration, for the org.eclipse.wildwebdeveloper.css content-type whether "Auto-Closing pairs" seem correct and the "Enable auto-closing" checkbox is checked?

**Comment by jabby** [comment] 2019-03-27 09:16
Works for me too with: 

```
  ASM Core	7.0.0.v20181030-2244	org.objectweb.asm	Eclipse Orbit
  Buildship: Eclipse Plug-ins for Gradle	3.0.0.v20181106-1441-m	org.eclipse.buildship.feature.group	Eclipse Buildship
  Debug Adapter client for Eclipse IDE (Incubation)	0.9.0.201903130753	org.eclipse.lsp4e.debug	null
  Dynamic Languages Toolkit - ShellEd IDE	5.11.0.201811220629	org.eclipse.dltk.sh.feature.group	Eclipse DLTK
  EclEmma Java Code Coverage	3.1.1.201809121651	org.eclipse.eclemma.feature.feature.group	Eclipse EclEmma
  Eclipse IDE for Java Developers	4.10.0.20181214-0600	epp.package.java	Eclipse Packaging Project
  Eclipse Java Development Tools	3.16.0.v20181206-1038	org.eclipse.jdt.feature.group	Eclipse.org
  Eclipse XML Editors and Tools	3.12.0.v201811192212	org.eclipse.wst.xml_ui.feature.feature.group	Eclipse Web Tools Platform
  Git integration for Eclipse	5.2.0.201812061821-r	org.eclipse.egit.feature.group	Eclipse EGit
  Git integration for Eclipse - Task focused interface	5.2.0.201812061821-r	org.eclipse.egit.mylyn.feature.group	Eclipse EGit
  Java implementation of Git	5.2.0.201812061821-r	org.eclipse.jgit.feature.group	Eclipse JGit
  JCodings	1.0.18.v20170306-1742	org.jcodings	Eclipse Orbit
  Joni	2.1.11.v20170306-1742	org.joni	Eclipse Orbit
  Language Server Protocol client for Eclipse IDE (Incubation)	0.9.0.201903130753	org.eclipse.lsp4e	Eclipse.org
  m2e - Maven Integration for Eclipse (includes Incubating components)	1.10.0.20181127-2120	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e
  m2e - slf4j over logback logging (Optional)	1.10.0.20181127-2120	org.eclipse.m2e.logback.feature.feature.group	Eclipse.org - m2e
  Marketplace Client	1.7.3.v20181205-1546	org.eclipse.epp.mpc.feature.group	Eclipse Marketplace Client
  Mylyn Builds Connector: Hudson/Jenkins	1.16.0.v20180403-2055	org.eclipse.mylyn.hudson.feature.group	Eclipse Mylyn
  Mylyn Context Connector: Eclipse IDE	3.24.2.v20180905-0014	org.eclipse.mylyn.ide_feature.feature.group	Eclipse Mylyn
  Mylyn Context Connector: Java Development	3.24.2.v20180905-0014	org.eclipse.mylyn.java_feature.feature.group	Eclipse Mylyn
  Mylyn Task List	3.24.2.v20180905-0003	org.eclipse.mylyn_feature.feature.group	Eclipse Mylyn
  Mylyn Task-Focused Interface	3.24.2.v20180905-0014	org.eclipse.mylyn.context_feature.feature.group	Eclipse Mylyn
  Mylyn Tasks Connector: Bugzilla	3.24.2.v20180905-0003	org.eclipse.mylyn.bugzilla_feature.feature.group	Eclipse Mylyn
  Mylyn Versions Connector: Git	1.16.0.v20170629-1738	org.eclipse.mylyn.git.feature.group	Eclipse Mylyn
  Mylyn WikiText	3.0.25.201806201740	org.eclipse.mylyn.wikitext_feature.feature.group	Eclipse Mylyn
  org.eclipse.lsp4j	0.7.0.v20190228-1517	org.eclipse.lsp4j	Eclipse LSP4J
  org.eclipse.lsp4j.debug	0.7.0.v20190228-1517	org.eclipse.lsp4j.debug	Eclipse LSP4J
  org.eclipse.lsp4j.jsonrpc	0.7.0.v20190228-1517	org.eclipse.lsp4j.jsonrpc	Eclipse LSP4J
  org.eclipse.lsp4j.jsonrpc.debug	0.7.0.v20190228-1517	org.eclipse.lsp4j.jsonrpc.debug	Eclipse LSP4J
  TextMate Core	0.3.2.201901202056	tm-feature.feature.group	Angelo ZERR
  Tip of the Day UI Feature	0.2.200.v20181107-2118	org.eclipse.tips.feature.feature.group	Remain Software
  Tycho Project Configurators	0.8.1.201704211436	org.sonatype.tycho.m2e.feature.feature.group	Sonatype, Inc.
  Wild Web Developer - Web edition in Eclipse IDE (Experimental)	0.3.0.201903262224	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project
  Xbase Runtime Library	2.17.0.v20190304-0518	org.eclipse.xtext.xbase.lib	Eclipse Xtext
```

**Comment by nimo23** [comment] 2019-03-27 11:17
The same goes for "html", "js(x)", "ts(x)". 
The Generic Editor does not auto insert the closing brackets in general.

**Comment by mickaelistria** [comment] 2019-03-27 11:19
@nimo23 Please details the version of `org.eclipse.tm4e.languageconfiguration` you have installed on your IDE.

**Comment by nimo23** [comment] 2019-03-27 11:31
The option "Enable auto closing brackets" is always enabled for all textmate-configs by default. However, auto-closing does not work for all of the files.

- Wild Web Developer v0.2.0.201903111934
- Eclipse IDE JEE, Version: 2019-03
- org.eclipse.tm4e.languageconfiguration: v0.3.2.201901202045

**Comment by mickaelistria** [comment] 2019-03-27 16:53
I just tried exactly the same thing: downloaded and installed Eclipse IDE for Enterprise Java developers, installed Wild Web Developer from Marketplace wizard, ended up with same version of Wild Web Developer and TM4E as you listed and could not reproduce.
While I don't challenge the existence of this bug, I'm clearly not able to reproduce it, hence fix it. It seems necessary that someone who actually has the issue debugs it. @vogella maybe?

**Comment by akurtakov** [comment] 2019-07-09 17:19
Do you guys still see the issue?

**Comment by nimo23** [comment] 2019-07-09 18:13
I upgraded eclipse and wwd - I dont see the issue anymore. Thanks.

**Comment by akurtakov** [comment] 2019-07-09 18:40
As per previous comment

**Closed by akurtakov** 2019-07-09 18:40 UTC
Labels: bug
