### ISSUE TITLE
[yaml] Insertion of some elements are done with tabs

### ISSUE THREAD

**Issue by apupier** [eclipse/wildwebdeveloper#478] opened 2020-07-17 09:10 UTC
the Yaml Language Server is using tabs in the provided completion content. Eclipse yaml client is using it as-is. it is causing invalid Yaml.

VS Code yaml is converting tabs to space automatically. (surely other editors?)

to reproduce:
- create a file named test.camelk.yaml
- add content:
```
# camel-k:
- 
```
- call completion and choose "from"
- created text contains the tabs, resulting in invalid yaml file.

![tabInsertedInYamlEditor](https://user-images.githubusercontent.com/1105127/87769421-eaf8c480-c81d-11ea-8b87-674b609f48dd.gif)

it would be nice to convert automatically in Eclipse IDE until the issue is fixed in Yaml language server https://github.com/redhat-developer/yaml-language-server/issues/283 unless it is fixed quickly in Yaml Language Server

nota: even when using "Insert spaces for tabs" is not working (I guess the generic text editor does not honor this setting but well this is abad thing to use space instead of tabs)

**Comment by mickaelistria** [comment] 2020-07-17 09:25
I think it's also related to #372 , and I believe the LS could be improved to remediate such faulty cases.

**Comment by apupier** [comment] 2021-08-05 15:45
pointed upstream issue  in teh other Wild Web Develope rissue # 372 has been closed: https://github.com/redhat-developer/yaml-language-server/issues/244 
Is there still something to do on Wild Web Developer side?

**Comment by mickaelistria** [comment] 2021-08-06 11:04
Let's close as duplicate of #372

**Closed by mickaelistria** 2021-08-06 11:04 UTC
Labels: upstream-yaml-language-server
