### ISSUE TITLE
a "goto component" line is added in angular template files.

### ISSUE THREAD

**Issue by jcompagner** [eclipse/wildwebdeveloper#708] opened 2021-08-07 16:13 UTC
And the first line becomes the second line but overwriting the second line not pushing everything down.

I think this does come from the angular language server (i use 12.2 working on top of the latest lsp4j/e code)

That goto component also doesn't do much i guess that needs to be implemented somewhere.

Any idea where i have to look to see if i can make a pull request?

**Comment by jcompagner** [comment] 2021-08-08 13:26
this is what i get:

![image](https://user-images.githubusercontent.com/3274268/128633501-df43fecf-41b8-47f2-b9c2-e8eca581ec98.png)

but this should be it:

![image](https://user-images.githubusercontent.com/3274268/128633514-59048668-aad8-4a6c-b88f-2a1c17da15e8.png)


so the first line does drop, but writes over the second, instead of everything going down.

But it seems that this is pure JFace code mining stuff?

![image](https://user-images.githubusercontent.com/3274268/128633537-1d80ce3b-0574-40f4-9e62-0f7380a8a055.png)


so could this be a JFace problem with that code mining stuff? or is there something else in lsp3e of wwd code?

**Comment by mickaelistria** [comment] 2021-08-30 10:07
The display issue with code minings in JFace. Can you please report the issue there?

**Comment by mickaelistria** [comment] 2021-08-30 10:09
I'm closing it here as there is nothing Wild Web Developer per se can change about that bug, this has to be fixed in JFace.

**Closed by mickaelistria** 2021-08-30 10:09 UTC
Labels: upstream-eclipse

**Comment by jcompagner** [comment] 2021-08-30 10:15
do you also see this problem?
The thing is as long as JFace has this problem (if the fix needs to be in there code) i think we should have an option to turn of this feature, because it is very annoying to have (besides that it doesn't work at all to click on "goto", that does need to be fixed i think in WWD)

**Comment by mickaelistria** [comment] 2021-08-30 10:22
> do you also see this problem?

I don't use Angular ;) But I imagine the problem is more generic and can be when a code mining is on the 1st line of a "small" file.

> The thing is as long as JFace has this problem (if the fix needs to be in there code) i think we should have an option to turn of this feature,

I hate workarounds. I'd rather invest in fixing the problem in JFace than reviewing a workaround; that is infinitely more profitable.
