### ISSUE TITLE
Syntax-coloring inside generic-text-editor partially unreadable

### ISSUE THREAD

**Issue by Ludwig-K** [eclipse/wildwebdeveloper#388] opened 2020-03-20 11:16 UTC
Hi,
I use "Wild Web Developer 0.8.3.202003111701" on Eclipse 2020-03, but had the same problems with older versions.

In combination with the Classic- or Light-Theme the Javascript-Syntax-Coloring is partially unreadable, because curly brackets, dots and text-selections are drawn with a white text-color on a white background.

No problem with dark-themes, but its not my favored style...

According to item #234 this could be changed by preferences->textmate->theme, but either i don't understand it or it has no effect.

Workaround:
Install Eclipse-Color-Theme plugin and select a light theme like f. e. "Roboticket", "Schuss", "Tango", "Notepad++ like"...

**Comment by jabby** [comment] 2020-03-20 12:32
Hello @Ludwig-K thanks for reporting your issue. 
I'm not sure I reproduce your problem on my laptop. 

* Can you add a screenshot of your problem?
* Can you give us the `Build Id Information` of your  Eclipse IDE? 
  * You can use Help > About Eclipse IDE > Right Click on text > Copy Build Id Information to clipboard.

Thanks.

**Comment by Ludwig-K** [comment] 2020-03-20 16:56
Screenshot of a .js-file in Generic Text Editor,  regard the invisible punctuation marks and brackets
![2020-03-20_17-47](https://user-images.githubusercontent.com/5821720/77186285-eec84480-6ad2-11ea-95d9-2d97bebebbd4.png)
Just for clearness the code of this screenshot:

```
 'use strict';
/**
 * Funktionen für das GIS Hinweis: Layersteuerung unter Lex.js
 * @type {Object}
 */
var Gis = {};

/**
 * verschiebt das DIV mit dem Maßstabsbalken delta_x/delta_y Pixel
 * 
 * @param {String}
 *            doc_id
 * @param {Number}
 *            delta_x
 * @param {Number}
 *            delta_y
 */
Gis.move_scalebar = function (doc_id, delta_x, delta_y) {
	var doc_gui_content_div, scalebar_image_div, start_left, start_top;
	doc_gui_content_div = document.body.querySelector("#my_frame_center > div[data-doc_id='" + doc_id + "']");
	scalebar_image_div = doc_gui_content_div.querySelector("div[data-func='scalebar_image']");

	start_left = parseInt(Dhtml.get_att(scalebar_image_div, 'start_left'));
	start_top = parseInt(Dhtml.get_att(scalebar_image_div, 'start_top'));

	scalebar_image_div.style.left = start_left + delta_x + 'px';
	scalebar_image_div.style.top = start_top + delta_y + 'px';
};
```
Eclipse IDE for PHP Developers
Version: 2020-03 (4.15.0)
Build id: 20200313-1211

Wild Web Developer: 0.8.3.202003111701

**Comment by nimo23** [comment] 2020-03-21 11:00
I also have this issue..that's the reason of https://github.com/eclipse/wildwebdeveloper/issues/235: I only use dark editor themes to make it readable..

**Comment by mickaelistria** [comment] 2020-03-22 13:58
I don't see this issue. Are you both using Windows? It could be a hint.
As far as I can see, on Linux, the "missing" part of the code that are invisible on your screen do use the default foreground color. If could be that for some strange reason, yours is set to White. Can you please check Window > Preferences > Editors > Text Editor > Appearance Color Options > Foreground color ?

**Comment by nimo23** [comment] 2020-03-22 15:10
>Are you both using Windows?

No, I use Mac Os with actual Eclipse IDE. 

>Foreground color ?

No, it is not set to white. It is correctly set to black (which is the default). 

I don't know if this matters: Maybe the DevStyle plugin (which I also use) rewrites some styles? I use DevStyle-Theme: Light Gray.

**Comment by jabby** [comment] 2020-03-22 17:50
I tried on Windows 10 with Eclipse Java Developer 2020-03 adn latests WWD plugin. 
There is no problem. 
Did you tried on a new fresh workspace?

**Comment by mickaelistria** [comment] 2020-03-22 20:33
> I don't know if this matters: Maybe the DevStyle plugin (which I also use) rewrites some styles? I use DevStyle-Theme: Light Gray.

Maybe. Can you please try the Eclipse IDE for JavaScript Developers from https://www.eclipse.org/downloads/packages/ , without installing DevStyle, and report whether you still see the issue?

**Comment by Ludwig-K** [comment] 2020-03-23 13:26
For the above screenshot I used a fresh install of Eclipse 2020-03 for PHP-Developers on an old workspace, OS: Linux (debian 10).

Window > Preferences > Editors > Text Editor > Appearance Color Options > Foreground color 
=> black

Test 1: new workspace/project/js-File with old eclipse-installation => same color-problems

Test 2: removed all hidden eclipse-settings (~/.eclipse, ~/.p2...), download and install "Eclipse 2020-03 for JavaScript Developers", created a new workspace/project and *.js-file 
=> no color-problems

Test 3: removed .metadata-folder and .project-file from old workspace, recreated php-javascript-project from existing source => no color-problems 

Attempt of explanation:
- incompatible settings of old workspace?
- perhaps some old workspace-settings from earlier WWD-installations?
- ...?

**Comment by mickaelistria** [comment] 2020-03-23 13:33
You're probably right about the fact that a previous faulty settings is "leaking" into the latest configuration. It's good to know that removing .metadata and ~/.eclipse helps. Those folders mostly store some preferences, next step would be to find out which one is affecting the rendering...

**Comment by Ludwig-K** [comment] 2020-03-23 13:46
Bad (?) news, bug reappeared, but now I know the reason:
After installing the above as "workaround" mentioned "Eclipse-Color-Theme"-plugin the color-problem reappeared, so the supposed "workaround" seems to be the real reason for at least my problem. 

Bad news part 2: uninstalling the plugin does not help, I had to remove the old settings and recreate the project.

**Comment by mickaelistria** [comment] 2020-03-23 13:51
I think it's actually good news as we find the culprit!
So you confirm that if Eclipse-Color-Theme is *not* installed, then color is OK; if Eclipse Color Theme is installed, color is incorrect?
If that's correct, and you have time, here is an exercise to try: get the IDE in a good state (good color), copy the .metadata folder; then install Eclipse Color Theme and see the bug in action, then compare the .metadata folder with the working one and identify the possible preferences that's responsible for this change.

**Comment by nimo23** [comment] 2020-03-27 10:08
>So you confirm that if Eclipse-Color-Theme is not installed, then color is OK;

I did not install eclipse-color-theme and by default the wwd **generic text editor** looks like this (which is very unreadable):

![generic-editor](https://user-images.githubusercontent.com/3045549/77744762-5d992680-701a-11ea-9b9b-08123fbc8771.png)

Please customize the theme colors for generic text editor to become more readable.

_Btw, this is the reason why I tried to customize the theme colors for the **generic text editor** by trying to adjust the themes with https://github.com/eclipse/wildwebdeveloper/issues/235#issuecomment-526503012. I wanted to achieve another theme per file ending to become more readable. But is also does not work._

**Comment by mickaelistria** [comment] 2020-03-27 11:12
> Please customize the theme colors for generic text editor to become more readable. I looked at the generic text editor with different file endings (html, js, css, jsx, tsx) - all are unreadable because of its default bright pastel colors. The default theme colors for generic text editor should be improved.

That's all a preference. I personally like those colors and prefer them over default one.
So your preference doesn't necessarily match other's preferences, and let's avoid sterile discussions of what should be the default unless there are clear objective data to support hat X is better than Y.

Have you tried Right-click>Switch to Theme... ?
If you wish to include support for more themes, please open a ticket to the https://github.com/eclipse/tm4e and consider contributing a patch. We can add a few additional themes in the default list if it helps, and we can even include a patch allowing to add a custom theme from the preferences.

I'm closing it for Wild Web Developer as it's not actionable here. I've suggested in #235 you open a new issue for the remaining potential bug; that should cover your story much better.

**Closed by mickaelistria** 2020-03-27 11:12 UTC

**Comment by nimo23** [comment] 2020-03-27 12:13
>That's all a preference. I personally like those colors and prefer them over default one.

Ok, you see personal preferences are different:) I think in general wwd should use the colors from the native eclipse theme as its default theme because this is the color theme which is prooven by a lot of people to be readable in the most cases (for example, people with color disabilities). 

>I've suggested in #235 you open a new issue for the remaining potential bug;

yes, I did it: https://github.com/eclipse/wildwebdeveloper/issues/395

**Comment by nimo23** [comment] 2020-03-27 12:40
>Have you tried Right-click>Switch to Theme... ?

I cannot find the "Switch to Theme"-menu on package explorer..
