### ISSUE TITLE
Run as Node program leaves launching Job behind at 37%

### ISSUE THREAD

**Issue by nitind** [eclipse/wildwebdeveloper#581] opened 2020-12-11 10:22 UTC
eclipse-javascript-2020-12-R-macosx-cocoa-x86_64 / Wild Web Developer 0.10.5.202012011111

If I launch a .js file using the Run as "Node program" option, after it has run to completion, even though the Console view shows the process as terminated, the Progress view and workbench trim show the Launching xxyy job at 37% until I manually cancel them.

**Comment by mickaelistria** [comment] 2020-12-11 10:27
Thanks for the report. I can easily reprodce it.

**Comment by mickaelistria** [comment] 2020-12-11 18:21
Here is a test that reproduces this issue

```java

	@Test
	public void testNodeRunDoesntLeaveProgressReport()
			throws CoreException, IOException, OperationCanceledException, InterruptedException {
		IProject project = ResourcesPlugin.getWorkspace().getRoot().getProject("someProject");
		project.create(null);
		project.open(null);
		IFile jsFile = project.getFile("hello.js");
		jsFile.create(new ByteArrayInputStream(new byte[0]), true, null);
		new NodeRunDebugLaunchShortcut().launch(new StructuredSelection(jsFile), ILaunchManager.RUN_MODE);
		DisplayHelper.sleep(500);
		Job launchJob = Arrays.stream(ProgressManager.getInstance().getJobInfos(false)) //
				.map(JobInfo::getJob) //
				.filter(job -> job.getName().startsWith("Launching")) //
				.filter(job -> job.getState() == Job.RUNNING) //
				.findFirst().get();
		launchJob.join(500000, null);
		assertEquals(Job.NONE, launchJob.getState(), "Job not completed");
	}
```

I could track that down to LSP4E, in DSPDebugTarget#initialize, the call to `getDebugProtocolServer().launch(dspParameters)` returns a never ending future.

**Comment by mickaelistria** [comment] 2020-12-11 20:18
This is indeed an upstream issue https://git.eclipse.org/r/c/lsp4e/lsp4e/+/173717 attempts to fix that.

**Comment by acarstoiu** [comment] 2020-12-18 23:14
Just for the record, this issue was discussed in #330 and also reported in #455.

**Comment by mickaelistria** [comment] 2021-02-18 17:18
Duplicate of #551 , let's close.

**Closed by mickaelistria** 2021-02-18 17:18 UTC
Labels: upstream-lsp4e

**Comment by mickaelistria** [comment] 2021-02-18 17:22
Duplicate of #551 , let's close.
