### ISSUE TITLE
Embed TypeScript Runtime

### ISSUE THREAD

**Issue by angelozerr** [eclipse/wildwebdeveloper#24] opened 2017-08-11 09:47 UTC
If https://github.com/mickaelistria/eclipse-bluesky/issues/22 is done, we could provide ambed TypeScript Runtime that user could change to use last TypeScript version (like I have done with typescript.java).

**Comment by mickaelistria** [comment] 2017-08-11 10:16
How many TS developers don't have tsserver installed? I believe simply
expecting tsserver to be in PATH and warn if missing would be enough.

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, at Red Hat Developers <https://developers.redhat.com/> community

**Comment by angelozerr** [comment] 2017-08-13 13:17
> I believe simply
expecting tsserver to be in PATH and warn if missing would be enough.

Customize the TypeScript sdk/runtime should be very good like VSCode does.

**Comment by mickaelistria** [comment] 2017-08-18 22:25
Embedding TS runtime is clearly something we should avoid as it causes more
issues that it fixes. Most ts developers have installed TS runtime by
themselves.
However, providing a preference to let end-user define another location for
TS runtime could be nice.
But I'm not convinced it's a high-priority issue at the moment.

**Comment by angelozerr** [comment] 2017-08-18 23:30
> Embedding TS runtime is clearly something we should avoid as it causes more
issues that it fixes. Most ts developers have installed TS runtime by
themselves.

VSCode works like this. It provides a default typescript sdk.

> However, providing a preference to let end-user define another location for
TS runtime could be nice.

With angular project generated with angular-cli, the typescript runtime is installed in the node_modules of your project. It's better to consume it instead of consuming an another ts runtime.

**Comment by mickaelistria** [comment] 2017-08-19 06:19
> VSCode works like this. It provides a default typescript sdk.

VSCode is implemented in typescript and is mostly and IDE for TypeScript,
so it can make sense in its specific case (just like NetBeans for Java EE
includes Glassfish). But it doesn't make it necessarily a good idea for the
Eclipse IDE IMHO.
We've have the experience with JDT or Maven: maintaining an alternative
implementation or shipping a piece of software that users do already have
or manage drives to confusion. For a while, there were lots of issues
report about m2e because users didn't get that the version of maven used by
Eclipse IDE wasn't the same than the one in PATH. I wouldn't like BlueSky
to reproduce this error.

> With angular project generated with angular-cli, the typescript runtime is
> installed in the node_modules of your project. It's better to consume it
> instead of consuming an another ts runtime.
>
From the Eclipse IDE perspective, we don't really care about the TypeScript
runtime. All we do is starting the LS with a `node` command:
https://github.com/mickaelistria/eclipse-bluesky/blob/master/org.eclipse.bluesky/src/org/eclipse/bluesky/JSTSLanguageServer.java
. The LS does embed the TS runtime it needs. It's up to the LS to pick the
right TS runtime and SDK according to project (can be the one in
node_modules).
I believe BlueSky isn't the right target for this proposal. The
javascript-typescript-languageserver is probably the piece of software
that's concerned by picking the right TS SDK.

**Comment by mickaelistria** [comment] 2018-12-16 20:46
I think we can close this one.
With #22 , typescript is now included in the dependencies and it seems like it's not a requirement for usage any more.

**Closed by mickaelistria** 2018-12-16 20:46 UTC
Labels: question
