### ISSUE TITLE
Eclipse 2022-03 pom editor nolonger using XML Editor indentation configuration

### ISSUE THREAD

**Issue by dantran** [eclipse/wildwebdeveloper#799] opened 2022-03-16 19:31 UTC
Please see  https://www.eclipse.org/lists/m2e-dev/msg02481.html

I think this bug is critical for those using the defactor Maven Pom indentation convention (2 space indent)

**Comment by mickaelistria** [comment] 2022-03-17 17:29
Duplicate of #240

**Closed by mickaelistria** 2022-03-17 17:29 UTC
