### ISSUE TITLE
Editing Javascript file can cause a hang

### ISSUE THREAD

**Issue by Lupicus** [eclipse/wildwebdeveloper#753] opened 2021-12-12 23:00 UTC
I mainly use Java, so I installed Eclipse Java 2012-12, but I occasionally need to work on Javascript in the same project, so I installed Wild Web Developer. When I set to use Generic Text Editor then I see syntax coloring, but typing anything seems to hang. My existing files are about 50 lines, but that doesn't seem to matter. I created a new project and told it to create a Javascript file and it added a comment section. It usually hangs just trying to type "var i = 0;". I let it sit there for 15 minutes and it was still locked up.
I see many exceptions in the log file, here are the 3 different ones, though truncated:

!ENTRY org.eclipse.lsp4e 4 0 2021-12-12 10:15:09.332
!MESSAGE java.util.concurrent.CancellationException
!STACK 0
java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException

!ENTRY org.eclipse.lsp4e 4 0 2021-12-12 10:15:10.933
!MESSAGE TimeoutException
!STACK 0
java.util.concurrent.TimeoutException

!ENTRY org.eclipse.lsp4e 4 0 2021-12-12 10:15:13.629
!MESSAGE org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: The pipe is being closed
!STACK 0
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: The pipe is being closed

Currently, I have to use the Text Editor to get any work done.

**Comment by mickaelistria** [comment] 2021-12-13 10:06
What's your OS? Are you using latest release of everything?
This "Pipe is beling closed" error could mean that the underlying language server stopped unexpectedly.

**Comment by Lupicus** [comment] 2021-12-13 10:22
Sorry, I forgot that info. I'm on Windows 7. I believe I have the latest that there is. I'll get my friend, which is using Windows 10 to load WWD and try it.

**Comment by Lupicus** [comment] 2021-12-15 23:34
The same setup on Windows 10 seems to work.

**Comment by Lupicus** [comment] 2022-01-19 03:14
Interesting. I have 2 different versions across 26 workspaces and they are above v13. When I get some time I'll see if I can replace one with v13 to see what it will do.

**Comment by JacquesLeRoux** [comment] 2022-01-19 06:45
Looking forward :)

**Comment by jabby** [comment] 2022-01-19 13:39
Hello, 

As far as I understand, the problem is related to the incompatibility between latest used version of Node.JS in  the plugin and Windows 7. I digged a little bit in Eclipse target environment support and I found that Windows 7 is no more supported since [Eclipse 2020-03](https://www.eclipse.org/projects/project-plan.php?planurl=http://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_15.xml#target_environments).

@Lupicus I think you can specify a different version of Node.JS and don't use the one embedded in Wild Web Developer by using `org.eclipse.wildwebdeveloper.nodeJSLocation` system property. cf. [TIPS and FAQ](https://github.com/eclipse/wildwebdeveloper/blob/7734ce2000c519c765b77f9a3668f638cdd0dc79/TIPS_and_FAQ.md#use-embedded-nodejs)

@mickaelistria I suggest to close this issue as nobody will invest time on supporting old OS. What do you think?

**Closed** 2022-01-19 13:44 UTC

**Comment by Lupicus** [comment] 2022-01-19 16:30
Thanks, using the property pointing to v13 seems to work!

**Comment by JacquesLeRoux** [comment] 2022-01-19 19:26
Thanks a lot,

Adding "-Dorg.eclipse.wildwebdeveloper.nodeJSLocation=C:\Program Files\nodejs\node.exe" to the eclipse.ini file works :)
