### ISSUE TITLE
hljs is undefined

### ISSUE THREAD

**Issue by lrozenblyum** [eclipse/wildwebdeveloper#654] opened 2021-03-23 08:54 UTC
Hello.
I'm facing a stable annoying JS error when editing a JS file in Eclipse.
OS: Windows10
Eclipse: 2021-03
Wild Web Developer: 0.10.6.202102181620

SCENARIO:
Edit a JS file, for example as simplest as
`Test.components.comp1 = {};`
Put mouse over 'comp1'.

EXPECTED:
No problems.

ACTUALLY:
A modal IE11-style popup is shown, with an error 'hljs in undefined'

**Comment by mickaelistria** [comment] 2021-03-23 08:56
I cannot reproduce it on Linux with latest snapshots.
Are you using the Generic Editor to edit the file?

**Comment by lrozenblyum** [comment] 2021-03-23 09:02
Yes, Generic Text Editor.
My OS is Windows10, maybe it has sth to do with that (the popup looks really similar to that one that is shown during JS errors in IE11, wondering why :) ).
![image](https://user-images.githubusercontent.com/1285898/112120643-24f94200-8bc7-11eb-851d-33dd11543f28.png)

The error in russian means: hljs is undefined

**Comment by lrozenblyum** [comment] 2021-03-23 11:15
Workaround: in IE11 settings to set checkbox 'Disable script debugging (other)'
Obviously it just hides the problem.

**Comment by akurtakov** [comment] 2021-05-12 06:47
Eclipse 4.19 supports using Edge https://www.eclipse.org/swt/faq.php#howuseedge . Maybe it will work better for you. AFAIK IE is on life support by MS even.

**Comment by akurtakov** [comment] 2021-05-12 06:50
Considering the highlight.js reply I would say go for edge. I'm closing this one as it's not smth this project does. You may consider opening a bug against swt if edge doesn't help.

**Closed by akurtakov** 2021-05-12 06:50 UTC
