### ISSUE TITLE
Source->Format can report error although file is correct (inconsistant doc state in LS?)

### ISSUE THREAD

**Issue by KlaasBonnema** [eclipse/wildwebdeveloper#650] opened 2021-03-18 14:33 UTC
WWD has a context menu Source (right click) with a Format sub-menu. If you use the Format menu then the bulk of your source code will be flagged with errors and the only way to restore is to reload a fresh copy of the source code (be warned!).

Version (Eclipse 2021-03)  Wild Web Developer	0.10.7.202103081410	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project

**Comment by mickaelistria** [comment] 2021-03-19 06:35
Can you please give a simple example of a file that gets corrupted when using format?

**Comment by KlaasBonnema** [comment] 2021-03-19 07:44
[bootstrap.zip](https://github.com/eclipse/wildwebdeveloper/files/6169384/bootstrap.zip)

Attached file (as released by bootstrap) will show the issue.
Open in WWD editor. Right click Source > Format. 
Now the editor will show numerous red spots at seemingly random places. 
What the command name implies - format the source code in some way - does not happen.

**Comment by mickaelistria** [comment] 2021-03-22 10:10
I can reproduce the error markers after formatting. So formatting seems to happen correctly (files are equivalent ignoring whitespaces, but the LS seems confused about the state of the file. Closing the file and reopening hides the (invalid) errors.

**Comment by janatgithub** [comment] 2021-06-30 13:12
> 
> 
> I can reproduce the error markers after formatting. So formatting seems to happen correctly (files are equivalent ignoring whitespaces, but the LS seems confused about the state of the file. Closing the file and reopening hides the (invalid) errors.

I have the exact same problem.
Using Eclipse Web JavaScript Developer Tools	3.22.0.v202103232331.

**Comment by jridge-ezclocker** [comment] 2022-02-13 05:41
I'm encountering a similar problem where the text editor (markers view, etc) shows errors for the javascript file but the file has no errors (validated no errors by viewing the same file with visual studio code). The errors seem very random and make no sense in context to the source code (see screen cap link for example).

[https://ibb.co/JsvwjGD](url)

This seems to start happening when CTRL+S (to save) is used, immediately followed by CTRL+F (format) and CTRL+S (to save again). Normally takes a pretty good size source file with about 700 lines or so (give or take). 

Interestingly enough, the habit of CTRL+S then CTRL+F and finally CTRL+S that seems to cause this problem could also get solved if the formatting was performed when the file was saved. I believe there is another issue written up asking for that ability.

I've seen this problem for most of 2021 and through now in 2022. So I don't think it was a recent version. To clear the bad errors I have to close and re-open eclipse (closing and reopening the editor does not clear the errors).

Another side effect is if I continue to edit the file with the bad error markers a future save and/or format command ends up corrupting the source code (removing the first letter of lines of code, applying incorrect formatting, and in general scrambling or deleting areas of the source code. In addition, undoing that format sometimes doesn't restore the lost code.
I assume it is due to the editor source being far out of sync with the source formatter. 

Watching the org.eclipse.lsp4e log it reports the following for the file (small edits to hide some information):

[t=1644730522084] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"4481","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///C:/dev/source/github.com/project/src/main/webapp/library/event-engine.js"},"position":{"line":745,"character":1}}}

[t=1644730522085] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"4481","result":[]}

[t=1644730522478] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 190

[t=1644730522479] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"4482","method":"textDocument/foldingRange","params":{"textDocument":{"uri":"file:///C:/dev/source/github.com/project/src/main/webapp/library/event-engine.js"}}}

[t=1644730522481] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"4482","error":{"code":-32603,"message":"Request textDocument/foldingRange failed with message: Error processing request. length < 0\nError: length < 0\n    at Object.createTextSpan (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:12061:19)\n    at TextChange.getTextChangeRange (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:172559:52)\n    at ScriptVersionCache.getTextChangesBetweenVersions (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:172633:66)\n    at LineIndexSnapshot.getChangeRange (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:172683:43)\n    at SyntaxTreeCache.getCurrentSourceFile (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:159590:48)\n    at Object.getOutliningSpans (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:160336:46)\n    at Proxy.<anonymous> (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript-template-language-service-decorator\\lib\\template-language-service-decorator.js:201:20)\n    at IOSession.Session.getOutliningSpans (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:171388:45)\n    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:170343:61)\n    at C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:172195:88\n    at IOSession.Session.executeWithRequestId (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:172186:28)\n    at IOSession.Session.executeCommand (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:172195:33)\n    at IOSession.Session.onMessage (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:172221:35)\n    at Interface.<anonymous> (C:\\Users\\...\\.p2\\pool\\plugins\\org.eclipse.wildwebdeveloper_0.5.20.202202041634\\node_modules\\typescript\\lib\\tsserver.js:174826:31)\n    at Interface.emit (node:events:390:28)\n    at Interface._onLine (node:readline:487:10)\n    at Interface._normalWrite (node:readline:661:12)\n    at Socket.ondata (node:readline:269:10)\n    at Socket.emit (node:events:390:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)"}}

Hopefully, it can be addressed as it makes for frustrating coding having to restart the IDE multiple times to avoid losing work. 

Let me know if any other info I can provide or things you wish to be to try to help debug. I'll try and check in as often as I can.

**Comment by KlaasBonnema** [comment] 2022-02-13 08:15
This started happening for me when I was forced to use WWD for editing javascript code instead of the previous editor that integrated perfectly with Eclipse but was dropped because it could no longer be maintained (new language constructs were no more added.)

The formatting problem happens mainly with large files. I routinely format other file types using the Source-> Format main menu (which is not present for WWD editor) but I am always carefull to not save right after that.
WWD has a right click context menu Source-> Format with a standardized shortcut Ctrl+Shift+F. (So Ctrl+F also seems to work?). 

For formatting javascript I now use other online javascript beautifiers/validators. That also has the advantage that you can specify your own formatting rules such as the position of { after or on the next line. (This is another capabillity that was lost with WWD.) The online tools can also flag more code issues or best practices than WWD (missing or unnecessary ; as an example.)
This clearly is not why I am using Eclipse as an integrated development platform.

WWD has more irritating behaviour such as always inserting two quotes, even when you insert them right before a string. I don't know who likes this behaviour, I keep deleting the extra quote that I did not insert myself. This is another deviation from how other editors in Eclipse behave and a regression from the previous javascript editor.

The cause for the formatting problem is indicated as: "LS seems confused about the state of the file". I don't know about LS or where it belongs but I would assume that either WWD developers are working on it to get it fixed or they have raised a problem entry with the proper LS developers. I don't see any indication of the latter.

What I do notice is that there seems to be a disconnect between WWD (development) and Eclipse (integration). One indication of that is that WWD updates appear asynchronously from Eclipse releases where other Eclipse modules tend to stick to the Eclipse release schedule.

**Comment by jridge-ezclocker** [comment] 2022-02-17 00:14
> That also has the advantage that you can specify your own formatting rules such as the position of { after or on the next line.

Just as an FYI:I've been controlling formatting options by including a .eslint.json configuration along with .checkstyle, .eslintignore. I also have .prettierignore, prettierrc.json and the eslint plugin for prettier installed in developer dependencies.

**Comment by mickaelistria** [comment] 2022-02-17 10:46
@jridge-ezclocker Interesting! Can you please contribute some guided steps to get good formatting into this documatation: https://github.com/eclipse/wildwebdeveloper/blob/master/TIPS_and_FAQ.md

**Comment by jridge-ezclocker** [comment] 2022-02-28 23:02
@mickaelistria Sure will - I'll try and get information in the file this week.

**Comment by mickaelistria** [comment] 2023-03-27 13:05
I just tried it and it seems to work all fine now. I'm not sure what of the language server or LSP4E resolved it, but still it looks resolved.

**Closed by mickaelistria** 2023-03-27 13:05 UTC
