### ISSUE TITLE
Unable to format SCSS and HTML files

### ISSUE THREAD

**Issue by LouieTian0209** [eclipse/wildwebdeveloper#517] opened 2020-09-10 02:29 UTC
I downloaded Eclipse 2020-06 for Web and Javascript Developers and installed WWD through Eclipse Marketplace. After post-installation reboot I opened an Angular project and I noticed that TypeScript files can be formatted fine whereas in SCSS and HTML files there's no option for formatting. When right clicking in the editor the Format (Ctrl+Shift+F) option is inactive and grayed out. Was wondering if this can be fixed by tweaking some config or if it needs internal changes for this to work.
P.S. I also tried opening an AngularJS project and I was able to format JS files but not SCSS and HTML files.

**Comment by mickaelistria** [comment] 2020-09-10 06:51
Duplicate of #38

**Closed by mickaelistria** 2020-09-10 06:51 UTC

**Comment by angelozerr** [comment] 2022-10-26 20:50
Once WWD will be released you could format HTML with this UI preferences

![image](https://user-images.githubusercontent.com/1932211/198134797-7c3fd845-8fdf-4049-a790-ef5d530acc20.png)
