### ISSUE TITLE
Completion and application freezed

### ISSUE THREAD

**Issue by jabby** [eclipse/wildwebdeveloper#11] opened 2017-04-20 15:00 UTC
Environment: 
Eclipse Platform
Version: Oxygen (4.7)
Build id: I20170126-1030
OS: Linux, v.4.10.9-200.fc25.x86_64, x86_64 / gtk 3.22.11
With bluesky

When I launched BlueSky in an Eclipse child, I tried the completion but it doesn't work.

How to reproduce

Use the folllowing snippet
````
var toto = [];
toto
````

* Add a "." and hit completion
* wait a little
* try to save the file
* The completion popup is still present and doing anything will end with a message about application responsiveness.

**Comment by stephan-herrmann** [comment] 2018-11-05 15:12
[wildwebdev.dead.txt](https://github.com/eclipse/wildwebdeveloper/files/2548941/wildwebdev.dead.txt)
I'm observing a frozen Eclipse instance, which could be the same as this existing bug report.

I was in the middle of typing some typescript code.

Note, that LSContentAssistProcessor is active in thread "main", waiting for a completable future - I assume that this has been triggered via syncExec from thread "AutoAssist Delay".

In thread "pool-6-thread-1" a FutureTask tries to write to an IOConsoleOutputStream, which blocks on streamAppended.

Also "EventAdmin Async Event Dispatcher Thread" tries to issue a syncExec - perhaps in response to streamAppended??? That would be a perfect deadlock.

**Comment by stephan-herrmann** [comment] 2018-11-05 15:16
As an aside, the number of active HighlightReconcilers roughly corresponds to replication of "Toggle Highlighting" buttons, as already mentioned in #84 (I have 14 such buttons, vs. 11 threads).

**Comment by mickaelistria** [comment] 2018-11-05 15:22
This is also a possible improvement in ContantAssistant.computeContextInformation(...) that could/should be invoked asynchronously to allow long-running operations and not block the whole IDE when it fails to get the value.
Also LSP4E's ServerMessageHandler.logMessage(...) could using another thread if this can cause deadlocks.

**Comment by stephan-herrmann** [comment] 2018-11-05 15:49
I think the logMessage() thing could be the core problem here. Since content assist is invoked on "main" it must be able to complete without requiring additional resources. Are you going to forward this to LSP4E?
One more detail: I have all Language servers configured with "LogToFile=false" and "LogToConsole=false". I would be immensely happy if that configuration would take effect ...

**Comment by mickaelistria** [comment] 2018-11-05 15:54
>  Are you going to forward this to LSP4E?

Yes probably. And if you are fine in doing it, please do it yourself now.
I think I'll also forward it to JFace. There is no good reason to invoke content assist from the main thread and for completionProposals, it's out of the UI-Thread. It should be the same for contextInformation.

> I have all Language servers configured with "LogToFile=false" and "LogToConsole=false". I would be immensely happy if that configuration would take effect ...

Those logging mentioned in preference are the LSP messages (all of them) mostly for debugging purpose. The `logMessage` operation of LSP is meant to show message in the tool, so it's not considering those preferences. But it could be a worthy addition, please create an enhancement request to LSP4E for that if you need it.

**Comment by norru** [comment] 2018-11-21 14:36
https://github.com/eclipse/corrosion/issues/128

**Comment by mickaelistria** [comment] 2019-03-13 07:32
Closing as cannot reproduce. I think several changes in LSP4E fixed that.

**Closed by mickaelistria** 2019-03-13 07:32 UTC
Labels: upstream-lsp4e
