### ISSUE TITLE
Javascript editing, go to matching bracket shortcut do not work

### ISSUE THREAD

**Issue by manoletto** [eclipse/wildwebdeveloper#1117] opened 2023-03-04 16:09 UTC
Ref : https://bugs.eclipse.org/bugs/show_bug.cgi?id=581621

May be i've found something to adjust :
After a lot of message in error log saying javascript-language-configuration.json not found.

In "...\eclipse\plugins\org.eclipse.wildwebdeveloper_1.0.3.202303031646\language-configurations\javascript\" folder
renaming "javascript-language-configuration.jsonc" to "javascript-language-configuration.json"
suppress error log message and matching brackets are highlighted.
But keyboard shortcut do not work.

In keys preferences, it's the CTRL+SHIFT+P shortcut.

Any idea why the cursor is not moved to the matching bracket ?

**Comment by vrubezhny** [comment] 2023-03-06 13:40
We actually have [javascript-language-configuration.jsonc](https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/language-configurations/javascript/javascript-language-configuration.jsonc ) configuration added and used. The mentioned rename has happened a while ago because of changing in the upstream project.

Could you, please, add the error messages from  your log here?

**Comment by manoletto** [comment] 2023-03-07 14:21
![image](https://user-images.githubusercontent.com/6593655/223449542-7d3bb13a-fd4c-482d-996b-48271b52f6f4.png)

**Comment by vrubezhny** [comment] 2023-03-07 14:44
Are these messages appeared after you renamed ` "javascript-language-configuration.jsonc" to "javascript-language-configuration.json"` ?

If it is tan this an expected result of such  a renaming.
The correct language configuration file name is [javascript-language-configuration.jsonc](https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/language-configurations/javascript/javascript-language-configuration.jsonc ) 

I'd recommend you to update from the latest snapshot: https://download.eclipse.org/wildwebdeveloper/snapshots/  and check the installed  `o.e.wildwebdeveloper` is really used in "`Help -> About -> Installation Details` 

In my environment the matching pair brackets are shown correctly. And I don't have any error messages like those you have pointed to.

The key combination `SHIFT+CTRL+P` is not set for Javascript Editor at the moment. So, do not expect it to start working  immediately after an update.

**Comment by manoletto** [comment] 2023-03-08 10:57
No, these messages are shown before i renamed to ".json". They are in error_log when file is named "javascript-language-configuration.jsonc".

Yes i already used the last snapshot :
![image](https://user-images.githubusercontent.com/6593655/223693505-3b6cb957-1af4-425a-978b-528fc6c196bf.png)

May be i need to install or uninstall another plugin, i don't know ...

I have these installed software :
![image](https://user-images.githubusercontent.com/6593655/223694073-41d6ea93-a4b7-4da9-b4d4-9e4cabce25f1.png)

The key combination SHIFT+CTRL+P is not set for Javascript Editor at the moment ... :-( 
I used this shortcut with PHP editor and when i edit a very long javascript file like jspdf.umd.js :
![image](https://user-images.githubusercontent.com/6593655/223694657-7548a638-c97a-4f75-9ae9-223e13b75ff7.png)

with 28833 lines of code, with the last line of code "})));" ... arghh ! where are the matching brackets ?! :-)

**Comment by mickaelistria** [comment] 2023-03-08 14:26
The renaming of internal files is totally not supported. Please provide steps to reproduce with a vanilla installation and nothing hacked.

**Comment by vrubezhny** [comment] 2023-03-08 14:42
I would suggest also updating the [TM4E](https://download.eclipse.org/tm4e/snapshots/) and [LSP4E](http://download.eclipse.org/lsp4e/snapshots/) from snapshots, and may be yes. re-installing the WWD

**Comment by manoletto** [comment] 2023-03-09 08:57
I'have install TM4E and LSP4E from snapshots, the shortcut don't go to matching brackets, anyway, does it work on your platform ?

**Comment by angelozerr** [comment] 2023-03-09 10:41
I create a PR on Platform https://github.com/eclipse-platform/eclipse.platform.text/pull/158 to support go to matchingbracket with Ctrl+Shift+P

**Comment by manoletto** [comment] 2023-03-10 11:48
@angelozerr Yes, when i set the cursor on a bracket, the matching one is highlighted.
Only the CTRL+SHIFT+P shortcut don't move the cursor ;-)

**Comment by angelozerr** [comment] 2023-03-10 11:55
Indeed I noticed this problem. I created a PR yesterday on eclipse platform to support ctrl shift p with generic editor which has been merged (thanks @mickaelistria)

**Comment by mickaelistria** [comment] 2023-03-10 16:52
Closing it here, it's actioned on Platform side.

**Closed by mickaelistria** 2023-03-10 16:52 UTC

**Comment by manoletto** [comment] 2023-03-10 17:14
Great, i see something has finally moved :-) I really thank you all.
