### ISSUE TITLE
Eclipse XML Editor Running Too Wild

### ISSUE THREAD

**Issue by enqueue** [eclipse/wildwebdeveloper#459] opened 2020-07-01 06:52 UTC
I installed Eclipse 2020-06 package for Java developers and added the Web Developer tools for better XML editing support. After a couple of minutes, `XMLServerLauncher` processes will start eating up my CPU cycles, even though I am not doing any heavy editing. After a while, Eclipse becomes unusable. I created a new workspace without copying any settings to make sure the issue was not caused by some legacy stuff in my projects or configuration.

Here you can see htop without any XML editing taking place (relevant processes shown):

![lemminx_htop_animated](https://user-images.githubusercontent.com/5407006/86212061-aad7e780-bb77-11ea-82ce-125ab3cc029d.gif)

I captured some memory and performance snapshots using yourkit, but I am not fit enough to identify the culprit in them quickly. I could upload them somewhere, if you think they would be useful in analyzing the problem.

Installation details attached (web developer plug-in version is 0.10.0.202006021616): [eclipse_configuration.txt](https://github.com/eclipse/wildwebdeveloper/files/4856171/eclipse_configuration.txt)

Sorry, if this is the wrong place to report the bug, but a friendly person at [@EclipseJavaIDE](https://twitter.com/EclipseJavaIDE) pointed me in this direction

**Comment by angelozerr** [comment] 2020-07-01 09:34
@enqueue I suggest you that you report your issue in https://github.com/eclipse/lemminx

If I understand you open a XML file, you does nothing and you have your problem? Please create an issue in https://github.com/eclipse/lemminx and explain in detail how we can reproduce your problem, which OS you are using and if you can add some other relevant information about memory, etc Thanks!

**Comment by fbricon** [comment] 2020-07-01 09:40
Please take a couple threaddumps (using jstack) when CPU is spiking

**Comment by fbricon** [comment] 2020-07-01 09:41
how many lemminx processes are running?

**Comment by enqueue** [comment] 2020-07-01 10:38
@angelozerr yes, it's just a dummy XML file, not very large. Will try to collect more info and report to the other project then.

@fbricon OK, will create some thread dumps. There is one `XMLServerLauncher` process, the htop output shows all user threads in the view above.

**Comment by angelozerr** [comment] 2020-07-01 15:59
Perhaps I'm wrong but I suspect the problem comes from LemMinx Maven when we see jstack (from https://github.com/eclipse/lemminx/issues/814 thanks to @enqueue) we can see `org.eclipse.lemminx.maven.searcher.RemoteRepositoryIndexSearcher` is called:

```
"ForkJoinPool.commonPool-worker-7" #18 daemon prio=5 os_prio=0 cpu=54406.23ms elapsed=425.45s tid=0x00007fa99c63e000 nid=0x1e61 runnable  [0x00007faa005ea000]
   java.lang.Thread.State: RUNNABLE
	at org.apache.lucene.util.IntroSorter.quicksort(IntroSorter.java:81)
	at org.apache.lucene.util.IntroSorter.quicksort(IntroSorter.java:87)
	at org.apache.lucene.util.IntroSorter.quicksort(IntroSorter.java:88)
	at org.apache.lucene.util.IntroSorter.quicksort(IntroSorter.java:88)
	at org.apache.lucene.util.IntroSorter.quicksort(IntroSorter.java:88)
	at org.apache.lucene.util.IntroSorter.sort(IntroSorter.java:41)
	at org.apache.lucene.util.BytesRefHash.sort(BytesRefHash.java:165)
	at org.apache.lucene.index.TermsHashPerField.sortPostings(TermsHashPerField.java:96)
	at org.apache.lucene.index.FreqProxTermsWriter.flush(FreqProxTermsWriter.java:91)
	at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:126)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:422)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:503)
	at org.apache.lucene.index.DocumentsWriter.postUpdate(DocumentsWriter.java:377)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:467)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1477)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1256)
	at org.apache.maven.index.updater.IndexDataReader.readIndex(IndexDataReader.java:101)
	at org.apache.maven.index.updater.DefaultIndexUpdater.unpackIndexData(DefaultIndexUpdater.java:387)
	at org.apache.maven.index.updater.DefaultIndexUpdater.loadIndexDirectory(DefaultIndexUpdater.java:202)
	at org.apache.maven.index.updater.DefaultIndexUpdater.access$300(DefaultIndexUpdater.java:76)
	at org.apache.maven.index.updater.DefaultIndexUpdater$LuceneIndexAdaptor.setIndexFile(DefaultIndexUpdater.java:518)
	at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:736)
	at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:161)
	at org.eclipse.lemminx.maven.searcher.RemoteRepositoryIndexSearcher.lambda$updateIndex$5(RemoteRepositoryIndexSearcher.java:235)
	at org.eclipse.lemminx.maven.searcher.RemoteRepositoryIndexSearcher$$Lambda$103/0x00000008002b9c40.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(java.base@11.0.7/CompletableFuture.java:1736)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(java.base@11.0.7/CompletableFuture.java:1728)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@11.0.7/ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@11.0.7/ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(java.base@11.0.7/ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@11.0.7/ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@11.0.7/ForkJoinWorkerThread.java:177)

```

@mickaelistria @AObuchow do you think it could be the problem?

**Comment by AObuchow** [comment] 2020-07-01 16:05
@angelozerr it very well could be that LemMinX-Maven is downloading the index from Maven Central.

IMO there should be a preference to disable lemminx-Maven from downloading the index (m2e has such a preference but it’s not linked to LemMinX-Maven currently)

However another issue is that the index download is occurring when _not editing a pom file_.

**Comment by enqueue** [comment] 2020-07-01 16:37
Hello guys, you might be on the right track regarding the maven indexing.

This is what a recent YourKit CPU snapshot shows:

![cpu_profiling](https://user-images.githubusercontent.com/5407006/86269152-9f151100-bbc9-11ea-89c4-06309a7f62ae.png)

When starting XML editing, network traffic starts to kick in:

![dstat_eclipse](https://user-images.githubusercontent.com/5407006/86269226-bc49df80-bbc9-11ea-8e53-0a1f8ab43446.png)

Now I quit Eclipse and network traffic is down

![dstat_noeclipse](https://user-images.githubusercontent.com/5407006/86269258-cbc92880-bbc9-11ea-93b8-43ec6ef5412a.png)

**Comment by AObuchow** [comment] 2020-07-01 16:54
@enqueue thank you for the very informative bug report!

I'm almost certain the issue is coming from[ LemMinX-Maven](https://github.com/eclipse/lemminx-maven).
As previously mentioned, I see two issues occuring:
1. LemMinX-Maven is starting to download the Maven Central index when processing a non-pom.xml file. @enqueue can you confirm that you hadn't didn't have any pom.xml files in your workspace?
2. There is no (working) way for a user to disable downloading the maven central index from m2e's preferences.

Bugs should be made for these two issues IMO (@mickaelistria WDYT?)

Other than uninstalling `POM Editor using LemMinX language server (includes Incubating components)`, you could wait for the maven central index to download as a temporary workaround. The central index is roughly 2.5gb big - it can take roughly 10 minutes to download depending on your internet connection speed.

**Comment by enqueue** [comment] 2020-07-01 17:26
Thanks everybody for your quick response! That's really great for an open source project :heart: 

As I wrote, I started with a pristine workspace and created a generic project in it. However, the Eclipse for Java Developers package, which I am using as a basis, includes m2e, of course, and you see all kinds of maven things being added to the class path in the process list for `XMLServerLauncher`

I can try and add some memory to eclipse.ini, wait a little bit more.

**Comment by enqueue** [comment] 2020-07-01 18:15
I waited for the download to finish and some process to consume considerable CPU time. After a while, the processe calmed down.

However, the same thing happens again after restarting Eclipse. Although the index `~/.lemminx/repo.maven.apache.org1923549499-index` seems to be touched during the process, it looks like a re-build is taking place. I was unable to find the right version of Luke to look into this Lucene index, so I could have investigated further. The index is still small (ca. 32 kb).

Where else should I look?

**Comment by mickaelistria** [comment] 2020-07-03 08:10
Do you have 1 XMLLanguageServer process or multiple ones started?

**Comment by enqueue** [comment] 2020-07-03 08:34
It's _one_ process, at least I have not observed multiple instances. Sorry if my first screenshot is misleading; it's `htop` output with one line per user thread.

**Comment by joeshannon** [comment] 2020-09-02 10:09
We have just been starting to experience what I believe to be the same issue after switching to 2020-06 (specifically Eclipse for RCP and RAP developers). 

I haven't fully investigated the triggers for this but as mentioned elsewhere it appears to happen possibly whenever an xml file is edited - the Eclipse projects themselves are not Maven projects (they are mostly Eclipse plugin projects).

The bigger problem for us is the amount of space that `~/.lemminx` uses. We are limited to 8 GB networked home directories so a 2.5 GB index is a significant chunk of this.

I was just wondering if there are any known solutions/workarounds to this so far, for example disabling the index download or possibly changing its location? 

Otherwise the only option I can see at the moment is symlinking that directory to somewhere e.g. under `/tmp`.

**Comment by angelozerr** [comment] 2020-09-02 10:19
> I haven't fully investigated the triggers for this but as mentioned elsewhere it appears to happen possibly whenever an xml file is edited - the Eclipse projects themselves are not Maven projects (they are mostly Eclipse plugin projects).

The bigger problem for us is the amount of space that ~/.lemminx uses. We are limited to 8 GB networked home directories so a 2.5 GB index is a significant chunk of this.

I think the problem comes from https://github.com/eclipse/lemminx-maven/issues/133

**Comment by mickaelistria** [comment] 2020-09-03 15:26
I don't think there is anything Wild Web Developer can fix. The issue comes from m2e which embeds LemMinX-Maven. So I'll close this issue.

eclipse/lemminx-maven#133 was fixed and lemminx-maven won't spend CPU and network downloading index until a pom.xml file is open. However, it won't reach m2e soon, you'll probably have to wait about a month before we propagate this change available in m2e and Eclipse IDE.

> We are limited to 8 GB networked home directories so a 2.5 GB index is a significant chunk of this.

I guess this case is not about Wild Web Developer, is it?

**Closed by mickaelistria** 2020-09-03 15:26 UTC
