### ISSUE TITLE
Turn off autocompletion and speed up proposals

### ISSUE THREAD

**Issue by fujiokae** [eclipse/wildwebdeveloper#669] opened 2021-04-01 18:57 UTC
Someone posted a comment on the WWD Marketplace page but there is no reply. So, I'm posting here.
The automatic code assist activation is a great feature but the problem is it is slow and my typing is paused. So, I want to turn auto-activation off. But I can't find such an option. I use PHP, which allows me to activate the code assist by CTRL+space, so I want to have this functionality with WWD as well.

Also, while I don't fully understand how LSP works, it is also slow to popup proposals especially right after a JS file is opened. I guess the text editor connects to the Language Server(s) and pulls the information and caches it per JS file? The cache should be maintained for all JS files and at least during the session (while Eclipse is open). Maybe, it would be better to provide an option on how frequently the cache is refreshed (e.g. once a week or a month).

These two issues delay my coding so significantly that I'm still hesitant to switch from JSDT to WWD, which also means I have to stick with an old Eclipse as JSDT's code assist no longer works with the latest Eclipse.

**Comment by mickaelistria** [comment] 2021-04-01 19:11
> d my typing is paused.

This is not expected, computing completion happens in separate thread so typing should not be paused. Can you please report details about how to reproduce this issue?

**Comment by fujiokae** [comment] 2021-04-01 20:09
Thanks for a quick reply. Ok, there may be other factors that pause my typing. When I start typing, say, "Math.", there is a pause and the proposals popup shows "Computing proposals (0%)". And a second or two passes and I can resume typing. But when I continue typing, it is paused often. So, it's not just the code assist but maybe validation or something going on. Actually, while I'm typing, the Problems View is also refreshed frequently. So, it would be marked as an error when I just typed "Math.", which shouldn't happen. 
I have attached a screenshot when my typing was paused.
![2021-04-01 (1)](https://user-images.githubusercontent.com/34692638/113347983-018b7100-9304-11eb-9a9f-8413d5706399.png)


Anyway, WWD with the latest Eclipse is very slow. That is the main issue for me.

I use Eclipse 2021-03 (4.19.0) / Build id: 20210312-0638 on Windows 10 (64 bits) on a HP desktop.
The JS code in the screenshot has > 21,000 lines.
It probably has nothing to do with WWD but I turned off "Auto Activation" for the content assist for PHP and HTML.

**Comment by agentgt** [comment] 2022-08-26 16:42
I'm just stumbling on this myself. 

You should be able to disable as you type auto completion. In all my editors (vim, emacs, eclipse (other than wwd), vs code) I disable as you type suggestions/completion.

@mickaelistria is it possible?

**Comment by mickaelistria** [comment] 2022-08-26 16:48
> @mickaelistria is it possible?

At the moment no, and as far as I know, no-one has plans to implement that. It would have to be some extra preferences to add to Eclipse Platform most likely.

**Comment by nitind** [comment] 2022-08-26 16:53
> At the moment no, and as far as I know, no-one has plans to implement that. It would have to be some extra preferences to add to Eclipse Platform most likely.

Could you elaborate on the reasoning for that? The convention so far, and mentioned above in passing, is that editors in Eclipse provide control over this themselves.

**Comment by mickaelistria** [comment] 2022-08-26 17:18
> Could you elaborate on the reasoning for that?

I can't speak for everyone who doesn't contribute this; but my personal reason for not contributing it is that I think that if things are working well, then there is no reason to disable auto-completion if it's working well; and I prefer spending time on making things work well than on building workarounds for the cases it wouldn't work well. That would be putting lipstick on a pig to me, and so far, all my experience bring me to the conclusion that workarounds don't scale and are a disservice that distracts from real innovation and quality.

**Comment by agentgt** [comment] 2022-08-30 17:24
> I can't speak for everyone who doesn't contribute this; but my personal reason for not contributing it is that I think that if things are working well, then there is no reason to disable auto-completion 

It is not really disabling but rather changing the "Auto Activation". For an example of how it is supposed to work go see *Preference -> Java -> Editor -> Content Assist*  ... the default is only activate when `.` is pressed.

Eclipse has been like the above OOB for ever. Auto activation on *any* key is really annoying for me in general but I do not mind special keys like "." for Java.

Besides there is a work around anyway depending on which mode you are in. You just go disable the Language Server for whatever language (@nitind *Preferences -> Language Servers*). 

In my case it is the *new* maven pom file editor and thus disabling XML Language server worked.

The LSP server will throw endless exceptions **as I type**... with the suggestion window open. Of course even if it worked I still would not want it not popping up. The bizarre thing is the LSP suggestion window would still come up (and fail) for the WTP XML editor (IIRC was the original Maven POM editor).


```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jface.text.IDocument.removeDocumentListener(org.eclipse.jface.text.IDocumentListener)" because the return value of "org.eclipse.jface.text.ITextViewer.getDocument()" is null
    at org.eclipse.jface.text.link.LinkedModeUI.disconnect(LinkedModeUI.java:1073)
    at org.eclipse.jface.text.link.LinkedModeUI.leave(LinkedModeUI.java:1116)
    at org.eclipse.jface.text.link.LinkedModeUI.connect(LinkedModeUI.java:932)
    at org.eclipse.jface.text.link.LinkedModeUI.enter(LinkedModeUI.java:701)
    at org.eclipse.lsp4e.operations.linkedediting.LSPLinkedEditingReconcilingStrategy$1.runInUIThread(LSPLinkedEditingReconcilingStrategy.java:221)
    at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4345)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3968)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

If you are wondering why I haven't filed a bug about the above is because I'm not even sure which project to file it in: LSPe, LSP4J, WWD (here), or maven eclipse?

Anyway its a real shame that the original WTP XML editor I guess is deprecated when OOB it works more reliably particularly for Maven even if can't auto complete artifacts it can at least auto complete XML tags without exceptions.

**Comment by angelozerr** [comment] 2022-08-30 17:34
> In my case it is the new maven pom file editor and thus disabling XML Language server worked.

 Could you explain please why you wish to dosable XML langue server?

Your NPE problem should be fixed on LSP4E project but we need to understand why you have this trouble.

**Comment by mickaelistria** [comment] 2022-08-30 17:46
> The LSP server will throw endless exceptions as I type... 

Can you please open a separate issue about those exceptions? This is definitely something that should be fixed if it can be reproduced.

**Comment by agentgt** [comment] 2022-08-30 18:10
> Could you explain please why you wish to dosable XML langue server?

Well because it crashes. Eventually. I just turned it back on just now and it is working at the moment but eventually it fails. I will see if I can figure out how I can reproduce it. Once it does stop working it continues like that.

Furthermore the WTP XML editor (it does not use the Generic Editor framework) still does completion even with the XML Language server disabled.... and it can do formatting of XML... and the theming works so all the themes on Colorthemes will work... and you can change the indent policy... etc etc etc.

I'm happy to use the new WWD pom editor (or whatever its called) once it works and I appreciate all the work you guys are putting into it (or the LSP) but it currently is very much different than many of the original eclipse plugins including the "as you type suggestion" on any key.

Part of the reason I still use Eclipse (mostly Java) is mainly because I am used to it (20 years). So when things change greatly and/or lose features that I'm used to then Eclipse really loses value to me (and I think others).

Anyway looking at my logs here is a different exception that seems related;

```
!ENTRY org.eclipse.lsp4e 4 0 2022-08-24 10:20:51.922
!MESSAGE org.eclipse.lsp4j.jsonrpc.ResponseErrorException: The request (id: 1632, method: 'textDocument/completion') has been cancelled
!STACK 0
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: The request (id: 1632, method: 'textDocument/completion') has been cancelled
    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
    at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.computeCompletionProposals(LSContentAssistProcessor.java:109)
    at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:352)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
    at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:351)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: The request (id: 1632, method: 'textDocument/completion') has been cancelled
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
    at org.eclipse.lsp4e.LanguageServerWrapper.lambda$3(LanguageServerWrapper.java:270)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
    at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by angelozerr** [comment] 2022-08-30 18:39
@agentgt I understand your frustration and I m the kind eclipse user than you. I use Eclipse since 20 years and I like when it worked.

We try to provide the same feature than WTP XML editor and we start to have advanced feàtures like codelens or linked editing range to rename tage in inline editor.

But I m sad to listen to that you are not happy with XML language server and we need to fix troubles.

So please be patient and please report détailled issues in order to we can reproduce and fix them.

The real advantages with LSP is that we resoive à lot of issues and contributions coming from other ide/editor like vscode sublime etc

**Comment by agentgt** [comment] 2022-08-30 19:04
Thanks @angelozerr 

I'll see if I can follow up shortly with a reproducible project. I'm out for a few days but I'll try to prioritize getting something when I get back.

**Comment by angelozerr** [comment] 2022-08-30 20:08
IMHO I think cancel error should not be logged  since it can occur every time and it is not an expected error. It polluates error log.  Cancrl exception t is just a performance feature of the language server which is able to stop as soon as possible  the previoius completion process when user type a new character.

@mickaelistria what do you think about that?

**Comment by angelozerr** [comment] 2022-08-30 20:09
Thanks @agentgt for your understand. We wait for your feedback.

**Comment by mickaelistria** [comment] 2022-08-31 07:18
> IMHO I think cancel error should not be logged 

OK.

**Closed** 2023-03-27 11:00 UTC

**Comment by pounard** [comment] 2024-10-02 14:12
I also experience the very annoying auto activation behavior. I'm often typing something when it triggers, and make the editor ignore what I'm typing.

+1 for adding an option to disable auto completion auto activation as I type.

**Comment by mickaelistria** [comment] 2025-04-24 16:26
Help > Preferences > General > Editor > Generic Editor; uncheck "Enable auto activation".

**Comment by piradix** [comment] 2025-04-25 09:41
👍 Super it work, you save my live.

But the true path is 
`Help > Preferences > General > Editors > Text Editors > Generic Code Editor`
then  uncheck "Enable auto activation".
