### ISSUE TITLE
POM.xml format is incorrect.

### ISSUE THREAD

**Issue by charleech** [eclipse/wildwebdeveloper#1205] opened 2023-05-12 06:53 UTC
POM.xml format is incorrect.

### Environment

Windows 11 Home Single Language 22H2
Eclipse  version 2023-03 (4.27.0)
M2E - Maven Integration for Eclipse version 2.2.1.20230307-1553
M2E - POM Editor using LemMinX language server  version 2.0.3.20230202-1631
Wild Web Developer HTML, CSS, JSON, Yaml, JavaScript, TypeScript, Node tools version 1.1.0.202305041915
Wild Web Developer XML tools version 1.0.2.202301201156

### When highlight the already formatted from the begin of line and press `Ctrl` + `Shift` + `F`

![001](https://github.com/eclipse/wildwebdeveloper/assets/1825591/b5d13096-79ae-4564-a2fe-8565a0f03d56)
![002](https://github.com/eclipse/wildwebdeveloper/assets/1825591/6a5c3e7c-5621-41a7-9181-09473da69dad)

### Source pom.xml

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>my-group</groupId>
    <artifactId>my-artifact</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>my-artifact</name>

    <properties>
        <my.maven.assembly.version>3.5.0</my.maven.assembly.version>
        <my.maven.changes.version>2.12.1</my.maven.changes.version>
        <my.maven.checkstyle.version>3.2.2</my.maven.checkstyle.version>
    </properties>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>${my.maven.assembly.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-changes-plugin</artifactId>
                    <version>${my.maven.changes.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <version>${my.maven.checkstyle.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
```

**Comment by vrubezhny** [comment] 2023-05-12 18:54
@charleech  On Fedora 38, using the latest M2E-CORE 2.3.0 (not released yet, but probably you can install it from snapshot - https://download.eclipse.org/technology/m2e/snapshots/2.3.0/) + WWD 1.1.0 I cannot reproduce the issue.  Formatting happens to be applied only to the selected region and doesn't break the `<version>` tags unless I set `Max line with ` < 70 in preferences (when editing your example POM XML):

![Screenshot from 2023-05-12 20-38-14](https://github.com/eclipse/wildwebdeveloper/assets/620781/a86fb49b-37da-4460-8e45-7c6f779d8727)

Could you please check your `XML (Wild Web Developer)->Formatting` preferences and/or try installing the latest available versions (TM4E, M2E-Core, WWD).

**Comment by charleech** [comment] 2023-05-15 04:01
Apologize for late reply.

I've updated the following from the https://download.eclipse.org/technology/m2e/snapshots/2.3.0/

M2E - Complete Development Kit version 2.3.0.20230508-2140
M2E - Maven Integration for Eclipse version 2.3.0.20230508-2140
M2E - POM Editor using LemMinX language server (includes Incubating components) version 2.0.4.20230508-2140

Note: I have not updated the TM4E and let it to be the same as the original Eclipse version 2023-03 (4.27.0)

After re-test, the pom.xml with selected is formatted properly like a charm.

**Comment by akurtakov** [comment] 2023-05-15 05:38
Closing as per previous comment.

**Closed by akurtakov** 2023-05-15 05:38 UTC
