### ISSUE TITLE
Block indentation doesn't work

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/wildwebdeveloper#131] opened 2019-02-15 12:16 UTC
When trying to indent multiple lines using the <tab> key, nothing happens.

It should indent all selected lines by one tab.

In the plain generic editor it works and in the classic html, js, css editor too.

# Repro

Completely mark one or more lines and try to indent them via the <tab> key.

cc @vogella

**Comment by mickaelistria** [comment] 2019-02-18 17:19
What do you mean by "plain generic editor"?
The "Generic Editor" is actually a special editor which has an icon with curly braces. Is this the one you're referencing?
Then it seems to me that this is an issue of this "Generic Editor" for any file. Can you please open a bug to Eclipse Platform/Text?

**Comment by vogella** [comment] 2019-02-18 17:25
Works for me in the generic editor for a normal text file. Example:
Create file.txt
Add the following two lines:

````
This will change
This also
````

Mark both lines and press tab -> both lines are moved

**Comment by angelozerr** [comment] 2019-02-19 07:22
If it works with normal text file, but not with html file (after installing wildwebdeveloper), I suspect it's a bug coming from TM4E language configuration https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.languageconfiguration/src/main/java/org/eclipse/tm4e/languageconfiguration/LanguageConfigurationAutoEditStrategy.java (ex: NPE or other bug).

**Comment by mickaelistria** [comment] 2019-02-19 08:50
Thanks @angelozerr , I think you're right. A NPE was fixed some time ago in TM4E (but not released yet) and could be the cause of this issue.
@jonashungershausen @vogella Can you check which version of tm4e plugins are installed on your IDE? And then can you please try latest snapshot of TM4E and repeat whether it fixes or not?

**Comment by vogella** [comment] 2019-02-20 10:41
@mickaelistria I'm using http://download.eclipse.org/wildwebdeveloper/snapshots. Does that pull in latest snapshot of TM4E?

**Comment by vogella** [comment] 2019-02-20 10:45
@jonashungershausen works for me with latest snapshot.

````
document.writeln("<b>Bold Hello World via an external js file!</b>");
document.writeln("Testing");

// Stuff
````

**Comment by jonashungershausen** [comment] 2019-02-20 11:07
For me, the JS and the CSS (SCSS) editors work with the snapshot. 

The HTML editor doesn't for me. @vogella reports that his HTML editor works too. 

The only difference is his TM4E version, which is 0.3.1 while mine is 0.3.2.

I'm also using Spring Tools 4.1.1 which is based on Eclipse 2019-12.

**Comment by mickaelistria** [comment] 2019-02-20 12:42
> The only difference is his TM4E version, which is 0.3.1 while mine is 0.3.2.

What are the exact versions (including qualifiers)?

**Comment by jonashungershausen** [comment] 2019-02-21 12:29
TextMate Core	0.3.2.201901202056
  Wild Web Developer 0.2.0.201902181018

Not sure about @vogella.

**Comment by vogella** [comment] 2019-02-21 16:09
Just re-installed:

Eclipse TM4E	TextMate support in Java	0.3.2.201901202056	org.eclipse.tm4e.core
Eclipse Wild Web Developer project	Wild Web Developer: web development in Eclipse IDE	0.2.0.201902181018	org.eclipse.wildwebdeveloper

**Comment by jabby** [comment] 2019-02-21 18:27
@vogella @jonashungershausen 
Did you try with the same content in the editor? Did you use the same OS?

**Comment by vogella** [comment] 2019-02-21 18:44
Yes

Am Do., 21. Feb. 2019, 19:27 hat Gautier de Saint Martin Lacaze <
notifications@github.com> geschrieben:

**Comment by mickaelistria** [comment] 2019-08-21 21:00
Can you still reproduce it with recent builds?

**Comment by jonas-jonas** [comment] 2019-08-29 14:02
Unfortunately, yes @mickaelistria.

Version: 0.4.1.201907221412 from the Marketplace.

**Comment by mickaelistria** [comment] 2019-08-29 14:45
@jonas-jonas M3 EPP packages will be available for testing tomorrow. I'd be grateful if you can try the "Eclipse IDE for JavaScript and Web Developers" package and report whether it works for you with this package or not. I suspect some other plugin may override the tab behavior in your case.

**Comment by mickaelistria** [comment] 2019-08-29 16:49
M3 package is out. Please try https://ci.eclipse.org/packaging/job/simrel.epp-tycho-build/557/artifact/org.eclipse.epp.packages/archive/20190829-1310_eclipse-javascript-2019-09-M3-linux.gtk.x86_64.tar.gz

**Comment by jonas-jonas** [comment] 2019-08-30 07:04
Yes, it works in the M3 package. How would you advise on diagnosing this issue?

**Comment by mickaelistria** [comment] 2019-09-20 20:17
Closing as it seems to work with recent versions.

**Closed by mickaelistria** 2019-09-20 20:17 UTC
Labels: upstream-eclipse

**Comment by 4javier** [comment] 2020-02-14 18:53
I still got this problem on 
Spring Tool Suite 4 

Version: 4.5.1.RELEASE
Build Id: 202001211336
