### ISSUE TITLE
[YAML] Disable schema validation if no schema matching the open file is registered

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/wildwebdeveloper#216] opened 2019-08-07 17:49 UTC
In Dart projects a `pubspec.yaml` file is present containing project configuration.
Naturally it is opened in the YAML generic editor of WWD.

Upon first opening however there are syntax errors in the valid YAML file present (`Unexpected property environment` for example).
These are published by the language server. 
Oddly, they go away once the file was closed and then reopened.

Looks like WWD should tell the LS to not validate the file if there is no schema present?

**Comment by mickaelistria** [comment] 2019-08-07 21:25
interesting. Can you please check how this works for VSCode? We're actually reusing the LS for VSCode so this could either be a bug in the LS, or a wrong configuration of the LS.

**Comment by jonas-jonas** [comment] 2019-08-08 10:14
Works in VSCode for me. 

I was able to isolate this issue:
- Made a fresh install of Eclipse 2019-06
- installed only WWD
- created a `xx.yaml` file and pasted the following:
```
name: dsad
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Jonas Hungershausen <jonas.hungershausen@vogella.com>

environment:
  sdk: '>=2.4.0 <3.0.0' 
     
#dependencies:  
#  path: ^1.6.0   
  
dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0 
```

After looking around the codebase of WWD I noticed this: https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLLanguageServer.java#L55
Might be related, as it seems like the `validate` field is always set to true. Instead WWD should check if the file opened has a schema registered. 
Also the _Kubernetes_ schema is registered for all `.yaml` files? Shouldn't it only apply to kubernetes config files (though I'm not sure if they are identifiable?).

**Comment by mickaelistria** [comment] 2019-08-08 17:39
Ok. Do you think that the errors that are shown are errors that are caused by the Yaml LS trying to parse your file as Kubernetes?
I'll try to reproduce the issue in a test case, and then will try and upgrade of the yaml language server to see if it changes something. If not, I'll report the issue to the LS.

**Comment by jonas-jonas** [comment] 2019-08-08 17:57
> Do you think that the errors that are shown are errors that are caused by the Yaml LS trying to parse your file as Kubernetes?

It does look like it. There should not be any schema validation going on in the file.

> I'll try to reproduce the issue in a test case, and then will try and upgrade of the yaml language server to see if it changes something. If not, I'll report the issue to the LS.

That would be awesome. If you need anything else from my side, I'd be happy to help.

**Comment by mickaelistria** [comment] 2019-08-08 21:03
I was wrong by the way, we're using a different language server than VSCode here.

**Comment by mickaelistria** [comment] 2019-08-09 08:14
I could reproduce the issue in #217 
And it's an issue in the LS itself: https://github.com/redhat-developer/yaml-language-server/issues/173

**Comment by mickaelistria** [comment] 2019-08-09 14:26
Fixed with https://github.com/eclipse/wildwebdeveloper/commit/5469073eb6380c411c8f619e7c9e4dea6dfe5594

**Closed by mickaelistria** 2019-08-09 14:26 UTC
Labels: bug

**Comment by jonas-jonas** [comment] 2019-08-09 19:24
Woah, this was fast. Thanks a lot!
