### ISSUE TITLE
Rules in .eslintrc file are being completely ignored by ESLint.

### ISSUE THREAD

**Issue by cristianomoraes** [eclipse/wildwebdeveloper#530] opened 2020-09-21 04:28 UTC
The ESLint apparently is working. Not used parameters and misspelt commands are being pointed out correctly but the rules I defined in .eslintrc are being ignored.

I created the configuration files using `npx eslint --init`. I didn't add the `tsconfig.json` files once I am not working with Typescript.

My environment:
Ubuntu 20.04
Node 12.18.4
Eclipse 2020-09

[eslintrc.json.txt](https://github.com/eclipse/wildwebdeveloper/files/5253440/eslintrc.json.txt)
[package.json.txt](https://github.com/eclipse/wildwebdeveloper/files/5253441/package.json.txt)
![ESLint_not_working](https://user-images.githubusercontent.com/233792/93732887-85fb8980-fc27-11ea-8e50-7530bb447bd0.png)

If more information is needed, let me know.

Thanks

**Comment by mickaelistria** [comment] 2020-09-21 10:59
Can you please try to add a dummy mininal tsconfig.json just for testing? It could be that since the eslint plugin is provided as a tsserver extension, it expects such a tsconfig.json to detect the project root and as it's not there, fails at identifying the possible .eslintrc files.

**Comment by cristianomoraes** [comment] 2020-09-21 21:18
Hi,
Thank you for your answer. 
So I added a `tsconfig.json`. I tried the suggested config (https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper.tests/testProjects/eslint/tsconfig.json), then I tried an empty JSON file (just the curly brackets).
I also tried to add the TS configuration to .eslintrc. After each update, I restarted Eclipse just in case. But no one of these tries resulted in a different outcome.

Another thing is I just noticed that the error messages I am getting are not what I would expect. I am adding a gif showing that. 
I am also adding my dummy project in case it can help.

If there is anything else I can provide, please, let me know.

![wwd_issue](https://user-images.githubusercontent.com/233792/93821935-7a55a480-fcb3-11ea-92b7-a2fc337e985e.gif)
[test_project.zip](https://github.com/eclipse/wildwebdeveloper/files/5258145/test_project.zip)

**Comment by mickaelistria** [comment] 2020-11-24 21:06
This should now be fixed in snapshots. Can you please try them from https://download.eclipse.org/wildwebdeveloper/snapshots and reopen the issue if this is still failing for you?

**Closed by mickaelistria** 2020-11-24 21:06 UTC

**Comment by cristianomoraes** [comment] 2020-11-24 22:16
Hi @mickaelistria ,

Unfortunately, the problem still persists. I even remove all plugin and reinstall it using the link in your comment.

![image](https://user-images.githubusercontent.com/233792/100157525-9245e080-2f0f-11eb-9b5f-ff8a3630dfb8.png)

I don't know if it is relevant but I am using the Eclipse "Enterprise Java Developers" with only three extra plugins: "Darkest Dark Theme", "Jasper Studio" and the WWD.

I don't think I have the proper rights to Re-Open this ticket. But I can create a new one.

**Comment by mickaelistria** [comment] 2020-11-25 07:22
Can you please share the simplest example project to reproduce the issue (as an attachment or as a link to another repository)?

**Comment by cristianomoraes** [comment] 2020-11-25 19:09
@mickaelistria  This file I sent before https://github.com/eclipse/wildwebdeveloper/files/5258145/test_project.zip is the simplest I can provide to you.
The js script is in /WebContent/js folder.

**Comment by mickaelistria** [comment] 2020-11-25 20:20
Wild Web Developer is fine here; it looks like you project is somehow erroneous. To see that in action, just run `eslint .` on the project and you'll see rules are ignored. (you need `npm install -g eslint@latest` first if `eslint` isn't available in your PATH). Wild Web Developer is just another presentation for the output of `eslint` command here, so as long as this command doesn't give the right output, it's more a configuration problem on your project side.
I tried a few hacks to your project and couldn't find a way to get eslint reporting the expected results, even with CLI. You'll have to investigate. Good luck!

**Comment by cristianomoraes** [comment] 2020-11-25 20:55
Hi @mickaelistria thank you try to help me. That is odd because eslint is working for me so I am not sure that the problem:
![image](https://user-images.githubusercontent.com/233792/100280022-63da0b00-2fcc-11eb-9de9-57b6cd071a70.png)

But I still don't get the errors in Eclipse. 
![image](https://user-images.githubusercontent.com/233792/100280595-4c4f5200-2fcd-11eb-9663-5d613d3745ed.png)

I am probably doing something wrong, but I don't think the problem is the eslint.

**Comment by mickaelistria** [comment] 2020-11-26 08:43
Here is what I get locally
```
$ rm -rf test_project.zip teste/ && curl -L -o test_project.zip https://github.com/eclipse/wildwebdeveloper/files/5258145/test_project.zip && unzip test_project.zip && cd teste && npm install && eslint .
[...]
/home/mistria/sandbox/teste/WebContent/js/teste.js
  6:9  error  Parsing error: Unexpected token o

/home/mistria/sandbox/teste/teste.js
  6:9  error  Parsing error: Unexpected token o

✖ 2 problems (2 errors, 0 warnings)
```

Some more info
```
$ node --version
v14.1.0
$ npm --version
6.14.8
$ eslint --version
v7.14.0
```
and if you're using the node.js embedder from Wild Web Developer, it's node v12.16.1; eslint is not embedded (it's supposed to be using the one that's provided by your project).

I don't think we can expect ESLint in Wild Web Developer to behave correctly as long as CLI behaves inconsistently on different installations. You'll need to investigate what causes that in your project.
