### ISSUE TITLE
java.util.concurrent.CancellationException and no autocompletion after updating to   Wild Web Developer 0.10.6.202102181620

### ISSUE THREAD

**Issue by edertone** [eclipse/wildwebdeveloper#645] opened 2021-03-03 11:03 UTC
Recently upgraded my eclipse to the 

  Wild Web Developer	0.10.6.202102181620	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project

and since then, no autocompletion for TS files. The autocomplete popup window shows the following error:

java.util.concurrent.CancellationException

**Comment by mickaelistria** [comment] 2021-03-03 11:13
I cannot reproduce this issue locally.
Can you please download the IDE from https://download.eclipse.org/wildwebdeveloper/releases/latest/IDEs/ and describe detailed steps to reproduce the issue?

**Comment by edertone** [comment] 2021-03-03 13:08
Hi!

Downloaded the IDE from the link, and same problem.

Operating system is windows 7, if you want more details I can give you

**Comment by mickaelistria** [comment] 2021-03-03 13:17
Please share the workspace log and the language server logs (Window > Preferences > Language Servers > Logs)

**Comment by edertone** [comment] 2021-03-03 13:44
java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.computeCompletionProposals(LSContentAssistProcessor.java:105)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:352)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:351)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2396)
	at org.eclipse.lsp4e.LanguageServerWrapper.stop(LanguageServerWrapper.java:390)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:210)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:649)
	at org.eclipse.lsp4e.LanguageServiceAccessor.lambda$14(LanguageServiceAccessor.java:589)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:602)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.initiateLanguageServers(LSContentAssistProcessor.java:176)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.computeCompletionProposals(LSContentAssistProcessor.java:86)
	... 10 more

**Comment by mickaelistria** [comment] 2021-03-03 16:47
And what about the langauge server log?

**Comment by edertone** [comment] 2021-03-03 16:51
Sent by email

**Comment by mickaelistria** [comment] 2021-03-03 16:55
It looks like the language servers are started, but they don't manage to talk via LSP.
Can you please look at the started subprocesses and copy the command that run them? Then please try running this command from CLI to see how it behaves.

**Comment by edertone** [comment] 2021-03-03 16:59
Which commands are you refering to?

**Comment by mickaelistria** [comment] 2021-03-03 17:22
Which processes/commands do you see as children of the Eclipse IDE when facing this issue?

**Comment by edertone** [comment] 2021-03-03 17:24
Do you mean on the windows tasks manager?

**Comment by mickaelistria** [comment] 2021-03-03 17:27
Yes.

**Comment by edertone** [comment] 2021-03-03 17:28
no new processes are shown at the windows task manager when trying to autocomplete and getting the error message

**Comment by edertone** [comment] 2021-03-05 08:20
Finally reverted the plugin update and everything worked again

**Comment by mickaelistria** [comment] 2021-03-05 08:31
Note that without more info to help reproducing and fixing the issue, you'll basically won't have newer Wild Web Developer versions (so newer TS, Angular and so) working anymore.
Please show all subprocesses of Eclipse IDE you see.

**Comment by edertone** [comment] 2021-03-05 09:56
"C:/Program Files/Java/jdk-11.0.8/bin/javaw.exe" -Dosgi.requiredJavaVersion=11 -Dosgi.instance.area.default=@user.home/eclipse-workspace -Dsun.java.command=Eclipse -XX:+UseG1GC -XX:+UseStringDeduplication --add-modules=ALL-SYSTEM -Dosgi.requiredJavaVersion=11 -Dosgi.dataAreaRequiresExplicitInit=true -Xms1024m -Xmx2048m --add-modules=ALL-SYSTEM -jar "C:\Program Files\eclipse\\plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar" -data file:/C:/Users/vmware/workspace-eclipse/ -os win32 -ws win32 -arch x86_64 -showsplash "C:\Program Files\eclipse\\plugins\org.eclipse.epp.package.common_4.18.0.20201210-1200\splash.bmp" -launcher "C:\Program Files\eclipse\eclipse.exe" -name Eclipse --launcher.library "C:\Program Files\eclipse\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.0.v20200915-1442\eclipse_11100.dll" -startup "C:\Program Files\eclipse\\plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar" --launcher.appendVmargs -exitdata f40_5c -product org.eclipse.epp.package.php.product -vm "C:/Program Files/Java/jdk-11.0.8/bin/javaw.exe" -vmargs -Dosgi.requiredJavaVersion=11 -Dosgi.instance.area.default=@user.home/eclipse-workspace -Dsun.java.command=Eclipse -XX:+UseG1GC -XX:+UseStringDeduplication --add-modules=ALL-SYSTEM -Dosgi.requiredJavaVersion=11 -Dosgi.dataAreaRequiresExplicitInit=true -Xms1024m -Xmx2048m --add-modules=ALL-SYSTEM -jar "C:\Program Files\eclipse\\plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar" 


"C:\Program Files\nodejs\node.exe" C:\Users\vmware\workspace-eclipse\.sonarlint\default\.sonartmp_17828951450566194767\eslint-bridge-bundle\package\bin\server 50123 127.0.0.1 C:\Users\vmware\git\TurboBuilder\TurboBuilder-Node true

**Comment by mickaelistria** [comment] 2021-03-05 09:57
No `node` process at all?

**Comment by edertone** [comment] 2021-03-05 09:58
it seems that when I try to autocomplete a node process appears for a moment as child of eclipse, but disappears in a second

**Comment by mickaelistria** [comment] 2021-03-05 10:04
OK, it would be great if you could find a way to capture the command it's trying to run and reproduce it in a terminal to get a better error message

**Comment by edertone** [comment] 2021-03-05 10:31
it's bee very difficult to catch the process info while it was alive, but here it is

node.exe	0.02	3.240 K	1.028 K	3280	Node.js: Server-side JavaScript	Node.js	C:\Users\vmware\workspace-eclipse\.metadata\.plugins\org.eclipse.wildwebdeveloper.embedder.node\node-v14.15.4-win-x64\node.exe "C:\Program Files\eclipse\plugins\org.eclipse.wildwebdeveloper_0.5.14.202102181620\node_modules\eslint-server\out\eslintServer.js" --stdio

**Comment by edertone** [comment] 2021-03-05 10:36
Says that system cannot find the specified path

**Comment by mickaelistria** [comment] 2021-03-08 07:58
This path is indeed incorrect.
I downloaded https://download.eclipse.org/wildwebdeveloper/releases/latest/IDEs/ on a Windows 10 VM I have locally and didn't face such issue. I also went through the code and didn't find anything obvious that could explain that some `\` are replaced by `.`.
It might be an issue in Eclipse Platform itself under some circumstances when it fails at creating the `Platform.getStateLocation(...)` folder. Do you reproduce the issue in other Windows installations?
'

**Comment by nitind** [comment] 2021-03-09 02:04
@mickaelistria It looks less like they were replaced, and more like the path was coded with a single `\` for separating directories under the workspace and that the `\`s were interpreted as escape sequences. The `.` are supposed to be there in the final path.

**Comment by mickaelistria** [comment] 2021-03-09 05:20
Thanks for the hint @nitind ! You're indeed right that `\` are simply missing. Are you able to reproduce this issue?

**Comment by edertone** [comment] 2021-03-09 07:38
If you want you can send me some patched files to test any possible fix

**Comment by nitind** [comment] 2021-03-11 04:20
> Thanks for the hint @nitind ! You're indeed right that `\` are simply missing. Are you able to reproduce this issue?

Unfortunately, no--I'm seeing node processes start correctly with 0.10.6.202102181620 out of eclipse-jee-2021-03-RC1-win32-x86_64.zip.

**Comment by crnormand** [comment] 2021-05-28 16:13
I get the same issue.    Ever since I upgrade Wild Web, NONE of my language servers will work.   I uninstalled Wild Web and uninstalled node.js and reinstalled the latest version of Wild Web 0.10.7.202103151818 and I get the same problem.

ava.util.concurrent.ExecutionException: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2093)
	at org.eclipse.lsp4e.LanguageServerWrapper.getServerCapabilities(LanguageServerWrapper.java:704)
	at org.eclipse.lsp4e.LanguageServiceAccessor.capabilitiesComply(LanguageServiceAccessor.java:282)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getInitializedLanguageServer(LanguageServiceAccessor.java:233)
	at org.eclipse.lsp4e.LanguageServiceAccessor.enableLanguageServerContentType(LanguageServiceAccessor.java:187)
	at org.eclipse.lsp4e.ui.EnableDisableLSJob.run(EnableDisableLSJob.java:45)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2475)
	at org.eclipse.lsp4e.LanguageServerWrapper.stop(LanguageServerWrapper.java:409)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:212)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:671)
	at org.eclipse.lsp4e.LanguageServiceAccessor.lambda$14(LanguageServiceAccessor.java:589)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:602)
	at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$2.run(ConnectDocumentToLanguageServerSetupParticipant.java:75)
	... 1 more

And then finally: LanguageServer not initialized after 10s

**Comment by mickaelistria** [comment] 2021-05-31 08:56
@cnormand Can you see the same behavior as described above regarding incorrect node command being triggered?

**Comment by crnormand** [comment] 2021-06-03 04:03
Sorry, I have no idea how I can capture the command line parameters for the node command.

**Comment by trevorkerby** [comment] 2021-10-17 16:30
>Windows 7

>node-v14.15.4-win-x64

I believe the embedded node, being that its version is greater than 13.6.0, will not work on windows 7 without setting `NODE_SKIP_PLATFORM_CHECK 1`, but I don't know how advisable this option is. Alternatively `-Dorg.eclipse.wildwebdeveloper.nodeJSLocation=path/to/your/older/node.exe` can be set in eclipse.ini to make Wild Web Developer work on the last decent version of windows :)

Tracking down this issue can take awhile, but maybe it could be made more apparent to users if the error `node.js is only supported on windows 8.1, windows server 2012 R2 or higher [...]` that node throws when attempting to run the newer versions on Windows 7 was reported in eclipse. It would be nice if this information were made more accessible somewhere, but I'm simply glad there's a workaround that doesn't involve committing to a full Linux workflow just yet. 

https://stackoverflow.com/questions/62212754/nodejs-for-windows-7

**Comment by mickaelistria** [comment] 2021-10-17 19:26
Thanks for the details @trevorkerby ! That is indeed a very probable cause; and it's not going to be better as Wild Web Developer new uses node 16.9.
Since we now have a root cause and a workaround, and no clear intent to better support Windows <= 7, I'm going to close this issue.
Adding the suggesting warning would be nice and a pull request that contributes it would be really welcome!

**Closed by mickaelistria** 2021-10-17 19:26 UTC
