### ISSUE TITLE
Eclipse Language server + XML support issue

### ISSUE THREAD

**Issue by shankarwww** [eclipse/wildwebdeveloper#406] opened 2020-04-15 15:16 UTC
Hi all,

I am getting this issue when i migrated from eclipse-jee-2019-12 to eclipse-jee-2020-03-R-incubation-win32-x86_64.

The error is:
Error while downloading 'http://java.sun.com/xml/ns/javaee/ejb-jar_3_0.xsd' to C:
\Users\sk\\.lsp4xml\cache\http\java.sun.com\xml\ns\javaee\ejb-jar_3_0.xsd.

Regarding proxy: i have not set any proxy parameter in eclipse. I am just using it inside a corporate bank office where the last version of eclipse was working fine. I have both eclipse in my machine and only this new version is causing issue.

**Comment by mickaelistria** [comment] 2020-04-15 15:18
Thanks.
Can you please first try latest release of Wild Web Developer (0.9.0, released earlier today) and verify whether the issue still occurs?
And if it occurs, can you please check the log files to see whether there are some interesting info?

**Comment by shankarwww** [comment] 2020-04-20 15:08
i did the updates as u said but issue remain the same

**Comment by shankarwww** [comment] 2020-07-03 17:48
Issue remains the same in the version 2020-06. When can we expect any fix ?

**Comment by mickaelistria** [comment] 2020-07-03 20:32
I personally cannot reproduce your issue (I'm using Linux, so it could be a difference). It's not really possible to fix issues that cannot be reproduced.
Would you be interested in debugging that execution to find out clues about what can be the reason behind it?

**Comment by mickaelistria** [comment] 2020-09-11 19:59
Closing by lack of information to reproduce. Feel free to reopen with some more details if you can reproduce it with latest release.

**Closed by mickaelistria** 2020-09-11 19:59 UTC
