### ISSUE TITLE
Show error and log to Eclipse if tsserver could not be started

### ISSUE THREAD

**Issue by robmv** [eclipse/wildwebdeveloper#174] opened 2019-06-27 13:50 UTC
wildwebdeveloper was installed on a clean Enterprise Java Developers 2019‑06 package (for Linux). Using "Install New Software".

The new language servers are listed on the preferences "Language Servers" entry. Opening an existing TypeScript file, the editor tried is Geneic Text Editor (The others present are the Text Editor and External). There is syntax coloring, but no Outline, Code completion triggers an error on the log file:

```
!ENTRY org.eclipse.lsp4e 4 0 2019-06-27 09:41:00.742
!MESSAGE java.util.concurrent.CancellationException
!STACK 0
java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.computeCompletionProposals(LSContentAssistProcessor.java:96)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup$2.run(AsyncCompletionProposalPopup.java:352)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$8(AsyncCompletionProposalPopup.java:349)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
	at org.eclipse.lsp4e.LanguageServerWrapper.stop(LanguageServerWrapper.java:343)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:184)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:576)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:506)
	at org.eclipse.lsp4e.operations.highlight.HighlightReconcilingStrategy.collectHighlights(HighlightReconcilingStrategy.java:197)
	at org.eclipse.lsp4e.operations.highlight.HighlightReconcilingStrategy.lambda$0(HighlightReconcilingStrategy.java:124)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

There is a unrelated conficting keybinding message too:

```
!ENTRY org.eclipse.jface 2 0 2019-06-27 09:40:09.352
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2019-06-27 09:40:09.352
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3cf7433e,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@68cc6319,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
```

Do wildwebdeveloper requires node and tsserver on the PATH? Where does it locate them? i can't find a prepackaged node and tsserver on the Eclipse plugins directory

Edit: Reason found https://github.com/eclipse/wildwebdeveloper/issues/174#issuecomment-506752129

**Comment by mickaelistria** [comment] 2019-06-27 13:54
It requires `node` to be in PATH but should warn when it's not there. `tsserver` is embedded (not required).
What's the output of `node --version` for you?
Also, could you please try to prepared "Eclipse IDE for JavaScript and Web development" package directly at https://www.eclipse.org/downloads/eclipse-packages/ and see if it starts better?

**Comment by robmv** [comment] 2019-06-27 13:57
Fedora packaged Node.js

```
# node --version
v10.16.0

# rpm -qa nodejs
nodejs-10.16.0-3.fc30.x86_64
```

**Comment by robmv** [comment] 2019-06-27 14:37
With the another Eclipse package it fails with another exception, but it looks like is project layout dependent or my migrated workspace settings, because a new workspace and a new simple project, with an empty TypeScript file doesn't trigger it, and code completion options are shown. Will try to isolate if my project layout is the source of the problem. I have been using @angelozerr TypeScript IDE until now, so the projects layout was somewhat related to it.

```
!ENTRY org.eclipse.lsp4e 4 0 2019-06-27 10:29:06.834
!MESSAGE 
!STACK 0
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.getContextInformationAutoActivationCharacters(LSContentAssistProcessor.java:289)
	at org.eclipse.jface.text.contentassist.ContentAssistant.isAutoActivationTriggerChar(ContentAssistant.java:1200)
	at org.eclipse.jface.text.contentassist.ContentAssistant$AutoAssistListener.keyPressed(ContentAssistant.java:326)
	at org.eclipse.jface.text.contentassist.ContentAssistant$InternalListener.verifyKey(ContentAssistant.java:814)
	at org.eclipse.jface.text.TextViewer$VerifyKeyListenersManager.verifyKey(TextViewer.java:480)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:70)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5874)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1426)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1409)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1198)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6093)
	at org.eclipse.swt.custom.StyledText.lambda$1(StyledText.java:5787)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5874)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1426)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1409)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1450)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:819)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3978)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:857)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2238)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6814)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6132)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4166)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1429)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1585)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4661)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
```

**Comment by angelozerr** [comment] 2019-06-27 23:55
> I have been using @angelozerr TypeScript IDE until now

Thanks @robmv to migrate to Wild Web Developer. Could you share your project please? Where is your tsconfig.json file (on the root of your project?)

**Comment by robmv** [comment] 2019-06-28 14:21
Found the problem and is related to my workspace layout, not an specific project. I have a non conventional `node_modules` directory in my workspace directory. Wild Web Developer is using the tsserver from it, and have problems starting it, but the error is not shown to the user or logged on the standard Eclipse log file.

The error is only shown on stderr of the Eclipse main process. I noticed it when I made a copy of my workspace in order to trim it by pieces trying to find the cause, the error is:

```
Error: spawn /home/robert/test/node_modules/.bin/tsserver EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

There is no `/home/robert/test/node_modules/.bin/tsserver` because that `node_modules` directory is only a build process product. This allowed me when using TypeScript IDE to share modules between Eclipse projects without having to touch the TypeScript IDE source paths.

**Comment by stephan-herrmann** [comment] 2019-08-07 10:49
On a machine where previously WWD was working fine (version 0.1.0 at that time), I have a fresh install of WWD 0.4.2.201907300709 on top of Eclipse IDE for Java Developers 2019-06 (node is v8.10.0).

Any attempts to use typescript language server functionality is greeted with `TimeoutException` logged by lsp4e, and in the console I find:

    events.js:183
      throw er; // Unhandled 'error' event
      ^
    Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at Pipe.onread (net.js:628:25)
    events.js:183
      throw er; // Unhandled 'error' event
      ^
    Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at Pipe.onread (net.js:628:25)
    events.js:183
      throw er; // Unhandled 'error' event
      ^
    Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at Pipe.onread (net.js:628:25)

All this doesn't look very debug friendly.

Any suggestions how to investigate?

**Comment by mickaelistria** [comment] 2019-08-07 12:24
Wild Web Developer is not actively tested with node 8.x; but it is with node 10.12.
Maybe it's a node version issue. Can you please try upgrading node and report whether it works better? If it does, we'll narrow down the list of compatible node to remove 8.x

**Comment by stephan-herrmann** [comment] 2019-08-07 19:06
I had hoped I could use the default node version of my ubuntu LTS installation. Anyway, I found a (dubious) approach for installing 10.x, so now I have node v10.16.2. Don't tell me now that this is too new!

Now the latest WWD shows this in the outline:

    Request textDocument/documentSymbol failed with message: Cannot call write after a stream was destroyed.

Later, when I selected an identifier in a ts file, this was printed to the console (once):

    (node:21733) UnhandledPromiseRejectionWarning: Error: configure timeout
    at Timeout.Deferred.timer.setTimeout (/home/sherrmann/dev/bundle-pool-2017/pool/plugins/org.eclipse.wildwebdeveloper_0.3.2.201907300709/language-servers/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
    (node:21733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
    (node:21733) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I'm unable to say if this is better or worse than node 8.x

BTW: is it intended that the plugin o.e.wwd has a version that does not match the version of feature of the same name?

**Comment by stephan-herrmann** [comment] 2019-08-07 19:08
Interestingly, using the same node 10.6, WWD 0.4.0 (plugin 0.3.0.201906060852) works, which also failed with node 8.x.

**Comment by mickaelistria** [comment] 2019-08-07 21:38
> BTW: is it intended that the plugin o.e.wwd has a version that does not match the version of feature of the same name?

Yes, it's caused by semantic versioning.

I think your config should work. 
I'll try to look for similar error messages, but as I can't reproduce it locally, it's not going to be easy to fix.

**Comment by stephan-herrmann** [comment] 2019-08-08 12:54
Testing an another machine with a very similar configuration both 0.4.0 and 0.4.2 (from simrel staging) work fine. Tomorrow I will try to narrow it down on the original machine.

I just had hoped that failures would be explained by meaningful error messages, instead of this trial-and-error game.

**Comment by stephan-herrmann** [comment] 2019-08-09 10:04
Looks like the problem is not machine specific, but workspace specific, perhaps similar to what @robmv found out. In the problematic workspace I do have a node_modules directory in a project. This project does *not* contain any language server stuff, and the error in the console is indeed triggered from org.eclipse.wildwebdeveloper_0.3.0.201906060852/language-servers/node_modules/typescript-language-server/lib/utils.js, i.e. the bundled language server.

Now, could it be that the language server then resolves dependencies from my workspace (perhaps with mismatching versions)? Why should the contents of the workspace influence the tooling itself (does it?)?

**Comment by stephan-herrmann** [comment] 2019-08-09 10:14
In the affected project, removing / renaming both `node_modules/` and `tsconfig.json` "fixes" the problem with the language server. 

Bonus question: how could I possibly figure out, what exactly breaks the language server?

**Comment by mickaelistria** [comment] 2019-08-09 13:22
Thanks a lot for your investigation @stephan-herrmann . While I don't have an answer to your questions, I think the clues you've found are driving us towards those answers, and a solution.
Can you please share some example of a project (with `node_modules/` and `tsconfig.json` that has such issue)? From here, we could write a test case and find the answers via debugging.

**Comment by wnm3** [comment] 2019-10-24 20:11
Not sure if this is related or not (I do have projects with node_modules...). I get unwanted consoles with this message in them and would like to disable these consoles.
[Error]	[tsserver] env: node: No such file or directory

Node is accessible via the eclipse.ini entry:
-Dorg.eclipse.wildwebdeveloper.nodeJSLocation=/usr/local/bin/node
and Node version is: v12.13.0

**Comment by wnm3** [comment] 2019-10-25 12:42
I had reinstalled node using the approach here: https://www.hostingadvice.com/how-to/update-node-js-latest-version/ following the Package Manager instructions:
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

It seems to be installed correctly and accessible from the PATH:
```
(base) ~$which node
/usr/local/bin/node
(base) ~$node -v
v12.13.0
(base) ~$
```
On MacOS, the PATH from .bash_profile is not provided to launched applications -- why I had to ad the eclipse.ini entry mentioned above. Perhaps whatever is bitching about No such file or directory is not reading that JVM defined variable?

Why this (fully qualified path to node executable) isn't a simple entry in the Eclipse Preferences escapes me. That approach would be the same for all operating systems and everyone needing to know how to launch it could pull from the preferences to avoid these inconsistencies.

**Comment by mickaelistria** [comment] 2020-07-09 23:02
Can you please try upgrading to https://download.eclipse.org/wildwebdeveloper/snapshots/ ? It now embeds node so the issue of failing tsserver is less likely to happen. Also  #302 and related ones were fixed some time ago, also drastically reducing the probablility of such issue to happen.
So I'm closing as I expect with latest snapshot, the faulty cases are almost always avoided, so there is no need to show the error any more.
If you face some issues with the linked snapshots, please open new tickets.

**Closed by mickaelistria** 2020-07-09 23:02 UTC
