### ISSUE TITLE
can't seem to run nodejs scripts in eclipse

### ISSUE THREAD

**Issue by glend1** [eclipse/wildwebdeveloper#330] opened 2020-01-21 18:38 UTC
I've written a script and im trying to run it to view it in the console in Eclipse but when I click the run button i just get a "Starting run session Launching program" message and it hangs at 37%. Whats wrong with my setup?

**Comment by mickaelistria** [comment] 2020-01-21 19:28
Can you please elaborate how you're trying to run this? What is your version of node.js?

**Comment by glend1** [comment] 2020-01-21 19:51
node version is v12.14.1. I am running it by pressing the run button in the toolbar. "node.js application", the configuration of which is mostly empty. ${workspace_loc:/sorter/app.js} as the main file and sorter as the project.

**Comment by mickaelistria** [comment] 2020-01-21 20:10
the default terms/values you're seeing seem different than usual Wild Web Developer ones; can you please share a screenshot?

**Comment by glend1** [comment] 2020-01-21 20:18
![Untitled-1](https://user-images.githubusercontent.com/8122900/72839965-2b222480-3c8b-11ea-9624-c54df397af3f.jpg)

**Comment by glend1** [comment] 2020-01-21 20:22
![Untitled-1](https://user-images.githubusercontent.com/8122900/72840253-bdc2c380-3c8b-11ea-9d70-20a1988f9878.jpg)

**Comment by mickaelistria** [comment] 2020-01-21 20:23
This Launch configuration is not from Wild Web Developer. Please the other one (with lower-case 'a' in "application").

**Comment by glend1** [comment] 2020-01-21 21:04
That one does the same thing. Environment is empty and Debug adapter is also empty (override defaults is unchecked).

**Comment by glend1** [comment] 2020-01-22 14:37
Did a complete reinstall of eclipse removed all previous artifacts too. installed "Eclipse IDE for JavaScript and Web Developers" of eclipse and WWD. I get the same error, this time there is no configuration from the config window.
![Untitled-1](https://user-images.githubusercontent.com/8122900/72903205-bdc2d200-3d24-11ea-8694-c0fede914783.png)

**Comment by mickaelistria** [comment] 2020-01-22 15:02
Can you please create a configuration and fill it wit the expected values and see what happens?

**Comment by glend1** [comment] 2020-01-22 16:34
The script runs. However, im still stuck with a never ending progress bar, it says "starting run session: initializing connection to debug adapter"

**Comment by PyvesB** [comment] 2020-01-22 19:42
I've also observed this quite a few times, even though I don't use these NodeJS script launches often.

**Comment by mickaelistria** [comment] 2020-03-13 04:45
I'm closing this one as Node.js scripts do run.
Please open a separate ticket for non-ending progress bar.

**Closed by mickaelistria** 2020-03-13 04:45 UTC

**Comment by emrecio** [comment] 2020-06-06 21:41
I know this issue is closed, but I am having the identical problem. I created a project, created one source file "foo.js" with two lines: "var foo = 1 + 1; foo;". When I click on run, it gets to 37% with "Starting run session: Launching program" and it just hangs there Eclipse 2020-03, Node (installed on /usr/local/bin) v 12.18.0. I copied and pasted this into node console, and it worked just fine.

**Comment by a82kd** [comment] 2020-06-07 11:53
Yes, I also have the same issue with this combination of versions

**Comment by acarstoiu** [comment] 2020-06-23 13:56
Please reopen this bug. I'm using latest Eclipse 4.16 with latest Wild Web Developer 0.10.0.202006021616 and I see this behaviour **every time** I launch a Node.js file, via the _Run As -> Node program_ context menu or a launch configuration of type _Node.js application_.

If the application has no output, the _Console_ view hangs as well. Otherwise, the app finishes just nice in the _Console_ view, but the progress bar remains active in the _Progress_ view.

**Comment by mickaelistria** [comment] 2020-06-23 15:32
@acarstoiu Please open a new ticket with as precise as possible steps how to reproduce.

**Comment by petesuch** [comment] 2020-09-29 04:19
here is a screenshot of what they are probably talking about...
![Screenshot - 9_29_2020 , 11_16_10 AM](https://user-images.githubusercontent.com/6709439/94512171-9c1bd200-0245-11eb-802d-c122dbdd522b.png)
![Screenshot - 9_29_2020 , 11_17_57 AM](https://user-images.githubusercontent.com/6709439/94512174-9d4cff00-0245-11eb-88a5-c23ee4e574ca.png)

**Comment by mickaelistria** [comment] 2020-09-29 07:37
@petesuch Can you try installing the node embedder from https://download.eclipse.org/wildwebdeveloper/releases/latest/ ?

**Comment by acarstoiu** [comment] 2020-11-10 22:45
Nope, that doesn't fix it. I'm running Wild Web Developer _**0.10.4.20200921215**_ on Eclipse _4.17_ and the behaviour stays the same, in the sense that the _Console_ view doesn't hang anymore but the progress bar of the task in the _Progress_ view hangs just as in @petesuch's screenshots.

**Comment by mickaelistria** [comment] 2020-11-11 07:35
Do I get it right that the node program does execute, and the issue is that the progress bar is still here?
If so, can someone check
* the running processes: is the node process still alive at that time
* run `jstack` and report the state of the various threads to sort out what can be locking this progress
?

**Comment by acarstoiu** [comment] 2020-11-11 10:41
Started a new Eclipse instance with one window in _Resource_ perspective with one JS file open, issued the **_Run_** command and waited to see what happens. I have three Node.js processes alive and a hanged progress bar indicator reading "Starting run session: Launching program". The console displays what was expected from the dummy program I ran and is labelled "\<terminated\>".

The output of
```
jstack -l -e 11492 > jstack.txt
```
is attached (_11492_ is Eclipse's PID).

[jstack.txt](https://github.com/eclipse/wildwebdeveloper/files/5523467/jstack.txt)

**Comment by mickaelistria** [comment] 2020-11-11 12:40
> I have three Node.js processes alive

Can you please share which commands were actually running?

**Comment by acarstoiu** [comment] 2020-11-11 14:56
I pressed _Run As -> Node program_ context menu on a simple file called _lang.js_. Nothing else, I kept it as simple as possible.

**Comment by mickaelistria** [comment] 2020-11-11 17:26
Sorry, I wasn't clear. I was more asking for the commands of the started node process, as they appear in your process list. This is to know whether the expected node process is active or not.

**Comment by acarstoiu** [comment] 2020-12-12 13:30
Sorry for the 1 month delay 😏 
After installing the latest Wild Web Developer _0.10.5.202012011111_, I tested again and can say that the launched Node.js program does **not** remain running, it is only Eclipse that thinks so.
So, it's just the _Progress_ view that is wrong.

**Comment by mickaelistria** [comment] 2020-12-12 14:07
Thanks for the feedback. The progress issue is tracked by #581 .
