### ISSUE TITLE
Compare editor formatting issue: tabs vs spaces

### ISSUE THREAD

**Issue by p-bakker** [eclipse/wildwebdeveloper#866] opened 2022-09-11 07:31 UTC
This is sort of a follow-up of #600

If I'm opening a .json file or a .ts file in the compare editor in Eclipse with WWD, then the formatting in the Compare editor is off when tabs are used for indenting: seems like the tabs are completely ignored/not displayed in the compare editor.

When I switch to plain Text Compare, at least the formatting of the code is correct (but you miss all the syntax highlighting features of course)

**Comment by mickaelistria** [comment] 2022-09-11 10:12
Can you provide details steps to reproduce this issue from a clean workspace? I just tried and could not reproduce it.
A first idea when reading the description is that the tabs are rendered with a width of 0 spaces in your case.

**Comment by p-bakker** [comment] 2022-09-11 16:16
> A first idea when reading the description is that the tabs are rendered with a width of 0 spaces in your case.

That indeed seems to be the case, cause if I turn on `Show whitespace characters`, they are being rendered at the beginning of each line, below the first non-tab character

**Comment by p-bakker** [comment] 2022-09-14 11:19
FYI: created a new workspace, new project, new .ts file with the following content:
```
function test() {
	// using a tab to indent
}
```

If I then open a Compare editor (Right-click > Compare with > Local History), it opens the compare editor in TypeScript compare (which is the Default Compare and even though the UI says it's on Text Compare) and it looks like this:
![image](https://user-images.githubusercontent.com/4981149/190140121-dcfc3f24-6786-45bb-b53b-2aa20679d39d.png)

If I switch to actual Text compare (using the three stacked dots button), I loose all syntax highlighting, but the indentation is done properly

**Comment by angelozerr** [comment] 2022-09-15 07:26
I can reproduce, I created a PR which should fix the problem at https://github.com/eclipse-platform/eclipse.platform.text/pull/86

**Comment by mickaelistria** [comment] 2022-09-15 07:50
Thanks a lot @angelozerr for the analysis and fix in Platform!

**Comment by mickaelistria** [comment] 2022-09-15 07:56
I'm closing it here since there is nothing Wild Web Developer can do about it, next step is https://github.com/eclipse-platform/eclipse.platform.text/pull/86 . @p-bakker you'll have to wait 3 months before this gets into a release, or -if you're eager to try it- you can start using Platform 4.26 I-Builds ;)

**Closed by mickaelistria** 2022-09-15 07:56 UTC

**Comment by angelozerr** [comment] 2022-09-15 08:00
> Thanks a lot @angelozerr for the analysis and fix in Platform!

You are welcome!

However I have a problem with syntax coloration when compare is done. On the left I have no syntax coloration and on the right it is good:

![image](https://user-images.githubusercontent.com/1932211/190349041-63155825-82ea-4e32-bcad-a09d51e90e3b.png)

@p-bakker have you the same problem?

**Comment by p-bakker** [comment] 2022-09-15 08:15
Tnx for the quick fix! 

> you'll have to wait 3 months before this gets into a release

Am afraid that due to some other dependancies, it'll be more like a year for me :-/ Something to look forward to though :-)

> have you the same problem?

At least not for .ts files. I also tried an html file, but I don't get syntax highlighting on either side, but maybe for me it doesn't use the correct Compare? When comparing HMTL, I don't get the 3-dot button to switch to a different compare mechanism, so I think it might just be doing a plain text compare
