### ISSUE TITLE
Refactoring throws fatal error

### ISSUE THREAD

**Issue by gbeneke** [eclipse/wildwebdeveloper#680] opened 2021-06-07 17:46 UTC
Refactoring does not work for me using even the simplest JS code snippets opened in the generic editor.  The error message shown is

![image](https://user-images.githubusercontent.com/85511748/121061647-66f85400-c7c4-11eb-8b84-7ed0e8e9d992.png)

For preview the same problem applies.  Finding references works and finds all variable references that need the refactoring applied.

Screenshot was taken testing the WWD supplied IDE on https://download.eclipse.org/wildwebdeveloper/releases/latest/IDEs/ .  Test was run on Fedora 34 (fresh installation just for this purpose on VirtualBox 6.1.22) but same result applies to Windows 10 (1809) native and with WSL 1 (Ubuntu 20.04) and Ubuntu 20.10.  On all platforms I run into the same problem.  Error messages differ depending on the JDK used.

Using the JEE Eclipse package which comes with WWD 0.10.6 prepackaged shows a different error message (in this case I use the OpenJDK 11.0.11 SDK to drive Eclipse):

![image](https://user-images.githubusercontent.com/85511748/121063843-1fbf9280-c7c7-11eb-9b98-abcd6fb11c17.png)

Error Log view:

![image](https://user-images.githubusercontent.com/85511748/121065016-94470100-c7c8-11eb-82a4-ae5a32394afb.png)

Complete stack trace in the Error Log view:

java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:397)
	at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog2.run(RefactoringWizardDialog2.java:324)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizard.internalPerformFinish(RefactoringWizard.java:636)
	at org.eclipse.ltk.ui.refactoring.UserInputWizardPage.performFinish(UserInputWizardPage.java:148)
	at org.eclipse.lsp4e.operations.rename.LSPRenameRefactoringWizard$RenameInputWizardPage.performFinish(LSPRenameRefactoringWizard.java:98)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizard.performFinish(RefactoringWizard.java:710)
	at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog2.okPressed(RefactoringWizardDialog2.java:450)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:468)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.lambda$0(RefactoringWizardOpenOperation.java:190)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:209)
	at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:126)
	at org.eclipse.lsp4e.operations.rename.LSPRenameHandler.lambda$2(LSPRenameHandler.java:78)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5067)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4573)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
Caused by: org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:76)
	at org.eclipse.ltk.core.refactoring.RefactoringStatusEntry.<init>(RefactoringStatusEntry.java:119)
	at org.eclipse.ltk.core.refactoring.RefactoringStatusEntry.<init>(RefactoringStatusEntry.java:87)
	at org.eclipse.ltk.core.refactoring.RefactoringStatus.addFatalError(RefactoringStatus.java:551)
	at org.eclipse.ltk.core.refactoring.RefactoringStatus.addFatalError(RefactoringStatus.java:538)
	at org.eclipse.lsp4e.operations.rename.LSPRenameProcessor.handleError(LSPRenameProcessor.java:189)
	at org.eclipse.lsp4e.operations.rename.LSPRenameProcessor.checkFinalConditions(LSPRenameProcessor.java:177)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.checkFinalConditions(ProcessorBasedRefactoring.java:226)
	at org.eclipse.ltk.core.refactoring.CheckConditionsOperation.run(CheckConditionsOperation.java:86)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:122)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:210)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2317)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by vrubezhny** [comment] 2021-06-25 12:39
For some reason LS server returns undefined response which leads to an NPE in lsp4e: https://git.eclipse.org/c/lsp4e/lsp4e.git/tree/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameProcessor.java#n173

Imho, NPE is to be fixed, however the real problem is in rename handler of TS LS, somewhere around https://github.com/theia-ide/typescript-language-server/blob/master/server/src/lsp-server.ts#L514 line.

**Comment by mickaelistria** [comment] 2021-06-25 14:12
@vrubezhny please make sure this issue is reported upstream and add a link from here to the report.

**Comment by mickaelistria** [comment] 2021-06-25 14:16
Note that the spec ( https://microsoft.github.io/language-server-protocol/specification#textDocument_rename ) says that null is a valid response. So LSP4E is also to blame here for not handling it correctly.

**Comment by vrubezhny** [comment] 2021-06-25 14:34
The issue is created to track the NPE in LSPRename Processor: "Bug 574470 - Refactoring throws NPE on rename operation when response is empty" - https://bugs.eclipse.org/bugs/show_bug.cgi?id=574470

**Comment by vrubezhny** [comment] 2021-06-25 15:09
The issue is create to track the Rename problem in TS LS: "Rename command doesn't work on TS LS" - theia-ide/typescript-language-server#225

**Comment by vrubezhny** [comment] 2021-06-30 13:42
The actual issue is in `@angular/language_service` plugin loaded by  `JSTSLanguageServer`: https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/JSTSLanguageServer.java#L58

In turn out hat `@angular/language_service` plugin overrides the normal behavior of some methods of TS `LanguageService` interface implementation and `findRenameLocations` is one of those methods that is used to find the rename locations in `Refactoring->Rename` operation, (see: https://github.com/angular/angular/blob/c7f9516ab920baee755d61ce0deea502e88a58ba/packages/language-service/src/ts_plugin.ts#L168):

```
  return {
    // First clone the original TS language service
    ...tsLS,
    // Then override the methods supported by Angular language service
    getCompletionsAtPosition,
    getQuickInfoAtPosition,
    getSemanticDiagnostics,
    getDefinitionAtPosition,
    getDefinitionAndBoundSpan,
    getTypeDefinitionAtPosition,
    getReferencesAtPosition,
    getSignatureHelpItems,
    findRenameLocations,    ///  <<<=== Line 168: Here the fileRemaneLocations method is overridden 
    getTcb,
    getComponentLocationsForTemplate,
  };
  ```
  However `@angular/language_service` plugin doesn't provide its own implementation for this overridden method, instead it contains a default 'empty' stub-like method (see: 
  https://github.com/angular/angular/blob/c7f9516ab920baee755d61ce0deea502e88a58ba/packages/language-service/src/ts_plugin.ts#L132):
  
 ```
   function findRenameLocations(
      fileName: string, position: number, findInStrings: boolean, findInComments: boolean,
      providePrefixAndSuffixTextForRename?: boolean): readonly ts.RenameLocation[]|undefined {
    // not implemented in VE Language Service
    return undefined;
  }
  ```
  ... which always return `undefined`, so the rename locations are never returned.
  
  So, the solution could be not use  `@angular/language_service` plugin in `JSTSLanguageServer` - at least temporary until the `findRenameLocations` API is implemented or this method is stopped to be overrode in the plugin.

**Comment by vrubezhny** [comment] 2021-06-30 14:46
The issue is create to track the Rename problem in `@angular/language_service` plugin: https://github.com/angular/angular/issues/42715

**Comment by atscott** [comment] 2021-07-01 00:50
@vrubezhny Browsing through some of the code, it appears that you also have a configuration which uses our language server and associates it with HTML and TS files: https://sourcegraph.com/github.com/eclipse/wildwebdeveloper@master/-/blob/org.eclipse.wildwebdeveloper/plugin.xml?L473-481

This seems like it should be enough to provide Angular Language Service capabilities. Could you try removing the `@angular/language-service` plugin from your `JSTSLanguageServer` and see if the Angular features still work? I don't think you should have both of these at the same time.

**Comment by vrubezhny** [comment] 2021-07-01 13:13
@atscott  As far as I could test it - it looks like you're right. We can remove Angular Language Service from JSTS LS and AngulatLanguageServer will provide all the capabilities for us. Maybe I missed anything in testing this but I think you're right.
AngularLanguageServer was introduced not that long ago, so JSTSLanguageServer was the  only server providing the Angular Language Service capabilities for the LSP-based editors. 

As far  as I tested, removing the `@angular/language-service` plugin from JSTSLanguageServer doesn't break any test (JUnit or manual), so I think AngularLanguageServer now provides Angular Language Service capabilities 

However I still think that your fix https://github.com/angular/angular/pull/42727 is to be merged.

**Comment by mickaelistria** [comment] 2021-07-02 19:45
Thanks @gbeneke for the report, @atscott for the discussion and @vrubezhny for the fix!

**Closed by mickaelistria** 2021-07-02 19:45 UTC
