### ISSUE TITLE
Chrome Debug Fails to Start

### ISSUE THREAD

**Issue by samyem** [eclipse/wildwebdeveloper#588] opened 2020-12-30 16:33 UTC
On Eclipse 2020-12 I have a react project that I am trying to debug with Chrome:
![image](https://user-images.githubusercontent.com/323450/103367147-58c63f00-4a92-11eb-8186-996fc871bc0c.png)

This results in the following error:
```
An internal error occurred during: "Launching chrome debugger".
Cannot invoke "java.io.File.getAbsolutePath()" because the return value of "org.eclipse.wildwebdeveloper.embedder.node.NodeJSManager.which(String)" is null
```
I got the following plugins:
![image](https://user-images.githubusercontent.com/323450/103367322-c70b0180-4a92-11eb-8c09-877909c65a05.png)

**Comment by mickaelistria** [comment] 2021-01-04 14:49
What OS are you using?
Can you please check in the `<eclipse-workspace>/.metadata/.log` file if there is additional content to help debugging?

**Comment by samyem** [comment] 2021-01-06 14:17
This is in Windows 10. The only error message in log is:
An internal error occurred during: "Launching chrome debugger".
Cannot invoke "java.io.File.getAbsolutePath()" because the return value of "org.eclipse.wildwebdeveloper.embedder.node.NodeJSManager.which(String)" is null

**Comment by vrubezhny** [comment] 2021-01-06 21:01
@samyem  Could you still provide the `<eclipse-workspace>/.metadata/.log` or a full stack trace if exist regarding the 'java.io.File.getAbsolutePath()` failure?
Also, could you please check if `Node.js for Windows x86_64` plugin fragment exists in your Eclipse instance? If not, do you have any Node.js version installed on your system?

**Comment by vrubezhny** [comment] 2021-01-11 21:35
@samyem Do you have Chrome selected in `Browser` tab of your launch configuration?

![chrome-debug-launch-config](https://user-images.githubusercontent.com/620781/104240720-cf811600-545c-11eb-8ede-a3050ef7d8bc.png)

I'm pretty sure in that if you select `Run with: Chrome` then it should normally start debugging.
It looks like it isn't selected by default, so you have to do it manually.
HTH

**Comment by samyem** [comment] 2021-01-11 21:39
Yes I have Chrome selected.

**Comment by vrubezhny** [comment] 2021-01-11 22:09
> Yes I have Chrome selected.

It looks like I've got what the problem is. Normally when installing a product on Windows, it's executables aren't added into a PATH if they aren't explicitly needed to be added.
Chrome Debug launch configuration, when searches for the Chrome executable, uses PATH system variable. So, even though `Chrome` is selected in `Browser` tab of launch configuration, it still couldn't be found on the system if its executable's folder is not added to the System or User PATH variable.

Please make sure you have added your Chrome executable folder to System or user PATH variable (don't forget to restart or at least to re-login after changing it) and try again.

**Comment by samyem** [comment] 2021-01-11 23:02
So yes it is not on Path but how come other IDEs like IntelliJ, VSCode etc works out of the box for the same feature?

**Comment by mickaelistria** [comment] 2021-01-12 08:25
I imagine other IDEs do look for it in typical installation directories.
It also seems to me that the configuration of your "Chrome" browser in `Window -> Preferences: General -> Web Browser` may be erroneous and should be fixed for this to work.

**Comment by vrubezhny** [comment] 2021-01-12 12:55
We wouldn't pay any attention to this Path story as we're going to get rid of that additional browser path calculation and rely only on the list of browsers defined in `General -> Web Browser` preference page,

In my case on Windows `General -> Web Browser` preference page contains a correct list of installed browsers on Windows. So, when `Chrome` is selected in `Run With:` field of Browser tab in launch configuration dialog (which means that a correct path to Chrome browser is provided to the launch) - it successfully starts the Chrome browser and the debugging session. Otherwise it fails to start.

@samyem  We still need to see your `.log` file to see what's really going on in your case - I can see/fix the issues I have on my system, but I have no I idea what's really your problem with the Chrome debug.

**Closed** 2021-01-14 17:39 UTC

**Comment by vrubezhny** [comment] 2021-01-14 18:29
@samyem Could you please try [the latest snapshot build](https://download.eclipse.org/wildwebdeveloper/snapshots/) to see if it fixes your issue? 
If it doesn't, please, feel free to reopen the issue and provide the latest `<eclipse-workspace>/.metadata/.log` file from your workspace.

Thanks
