### ISSUE TITLE
log file is written on each poll

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#315] opened 2019-12-25 19:34 UTC
I get the following logs in the eclipse console on each wwd-poll and it writes a log file for each poll in the eclipse/.metadata-folder. I did not configure anything with wwd. I only installed it and it makes such a noise by making polls and repeated logs:

```
[Info]	Using @angular/language-service v9.0.0-next.8 from /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.wildwebdeveloper_0.5.3.201912031954/language-servers/node_modules/@angular/language-service
[Warning]	Using less efficient polling watcher. Set TSC_NONPOLLING_WATCHER to true.
[Info]	Disabling language service for /Users/workspace/ide/test/src/main/webapp/WEB-INF/tsconfig.json because it is not an Angular project.
[Error]	No config file for /Users/workspace/ide/test/src/main/webapp/WEB-INF/node_modules/crypto-browserify/example/index.html
[Info]	Using typescript v3.5.3 from /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.wildwebdeveloper_0.5.3.201912031954/language-servers/node_modules/typescript
[Info]	Using @angular/language-service v9.0.0-next.8 from /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.wildwebdeveloper_0.5.3.201912031954/language-servers/node_modules/@angular/language-service
[Info]	Log file: /Users/workspace/ide/.metadata/angular-language-server-1577301845397.log
[Info]	Angular Language Service is running under DEBUG mode
[Warning]	Using less efficient polling watcher. Set TSC_NONPOLLING_WATCHER to true.
[Info]	Using typescript v3.5.3 from /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.wildwebdeveloper_0.5.3.201912031954/language-servers/node_modules/typescript
[Info]	Using @angular/language-service v9.0.0-next.8 from /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.wildwebdeveloper_0.5.3.201912031954/language-servers/node_modules/@angular/language-service
[Info]	Log file: /Users/workspace/ide/.metadata/angular-language-server-1577301871030.log
[Info]	Angular Language Service is running under DEBUG mode
```

On each poll, this log is shown and a log file is written in /Users/workspace/ide/.metadata/. I have found out that wwd writes over 3000 log files - so much garbage with same messages which can be avoided by default. Why does wwd makes so much logs and why does wwd-log says:

`Using less efficient polling watcher. Set TSC_NONPOLLING_WATCHER to true.`

Why does wwd not use the more efficient polling watcher by default when it already knows that it uses a less efficient polling watcher? 

`Disabling language service for /Users/workspace/ide/test/src/main/webapp/WEB-INF/tsconfig.json because it is not an Angular project.`

Why does wwd annoy me with such messages when wwd already knows that this is not an angular project?

**Comment by mickaelistria** [comment] 2020-01-06 10:39
This log file is created whenever the Angular Language Server starts (ie whenever a .js or .ts file is opened). The Language Server is too verbose, but I imagine there are ways to make the log silent.

Everything else is more internal to the Angular Language Server and isn't really something Wild Web Developer should act upon directly (but this should be forwarded to the Angular Language Server).

**Comment by nimo23** [comment] 2020-01-06 10:53
>This log file is created whenever the Angular Language Server starts (ie whenever a .js or .ts file is opened)

But not every project is an angular project. Is it possible to disable the _angular language server_ by default and enable it only if this project is indeed an angular project? For example by `right click on project->Configure->Add/Remove Angular Support`

**Comment by mickaelistria** [comment] 2020-01-06 10:58
> But not every project is an angular project. 

Sure, and Wild Web Developer and upstream stack currently lacks ability to decide of what project is an angular one and which one is not, and to start the language server conditionally.
But let's stick to the actual issue: the logs.

> Is it possible to disable the angular language server by default and enable it only if this project is indeed an angular project?

This would make things more complex for Angular users. Having to click in order to enable good capabilities isn't an acceptable workflow any more.
If you do not work with Angular at all, you can go to Preferences > Language Servers and uncheck the lines that mention Angular.

Let's hope for a more automated decision someday, but at the moment, this workaround is the best we can offer.

**Comment by nimo23** [comment] 2020-01-06 11:14
> If you do not work with Angular at all, you can go to Preferences > Language Servers and uncheck the lines that mention Angular.

Thanks. 

>But let's stick to the actual issue: the logs.

yes, actually only a minority of users use angular, the rest suffers from these logs..

**Comment by nimo23** [comment] 2020-01-06 11:23
>This would make things more complex for Angular users.

Only a minority of users use angular. However, disabling Angular support by `Preferences > Language Servers` is sufficient. This should stop the Angular Language Server and its logs.

**Comment by nimo23** [comment] 2020-01-23 11:12
It is a waste on my ssd when wwd polutes my workspace directory with hundreds of unsane `angular-language-server-1578587195259.log`..please switch that off.

**Comment by mickaelistria** [comment] 2020-01-23 11:24
Please provide a good patch for that, and I'll merge it immediately.

**Comment by nimo23** [comment] 2020-01-23 11:27
Sry, I would like, but I dont know about the internals of wwd and eclipse plugin developments.

**Comment by nimo23** [comment] 2020-01-23 11:57
My config shows already that my logs are disabled:

![wwd-logs-disabled](https://user-images.githubusercontent.com/3045549/72982617-c2988c00-3ddf-11ea-9d43-93364db0ca95.png)


But the above configs does not work, because logs are still written:

**Comment by nimo23** [comment] 2020-01-24 14:26
I also find out that these logs are not only written within the workspace-metadata directory but also **within the application-folder of MacOS** within eclipse.app->Contents/MacOs. **Actually wwd writes in the meantime over 2300 directories - each directory contains also a log file produced by wwd.**


```
ng_0cFUF3
ng_0jmWOI
ng_0QC4wb
ng_0XijvK
ng_1Hwfzz
ng_2A4b4M
ng_2akd29
ng_2In7lC
ng_2XdFlD
ng_3GK67Q
ng_3IFSSo
ng_6IXRyj
ng_6r0jlX
ng_7ARmlF
ng_7F4YwU
ng_7qT7cM
ng_8BJxCN
ng_8MWjqi
ng_9jjjg0
ng_9LDgiU
ng_9W3sNs
ng_21S5ed
ng_42YWBW
ng_55FRjT
ng_88b4oX
ng_AApA0j
ng_adfyYZ
ng_Aqyd5n
ng_aVEEXZ
ng_B5Di3o
ng_b7VTyK
ng_c5VG4t
ng_c7ZpB9
ng_C8pT0k
ng_cez77C
ng_chbntM
ng_cIC0Is
ng_cjXBLl
ng_cKKlqB
ng_Cot2l0
ng_cQortl
ng_ctgYzq
ng_CyxJy2
ng_d2LhUk
ng_dzjW3b
ng_E3RH3b
ng_E3vfQI
ng_EDxRt6
ng_EGy1ZX
ng_ER3Ki8
ng_eSBeCq
ng_eSVN95
ng_fa695V
ng_FdTIYn
ng_fG1gbE
ng_FTg8v1
ng_Fv13uf
ng_GaKvFv
ng_gaQKWx
ng_GgL2aB
ng_GkS8An
ng_gkVJ66
ng_GmY69c
ng_gS15HA
ng_hB318P
ng_HDMBGc
ng_hEnitx
ng_Hg8XsA
ng_hjh2Tv
ng_hw4tUH
ng_IrZi3y
ng_ixwyyu
ng_J1AjQP
ng_j1V1mu
ng_J3CB6p
ng_JDcEgg
ng_JLtiqi
ng_JsxQlJ
ng_JVAaWY
ng_KnbtYJ
ng_KNKIn3
ng_kPlDJM
ng_kPMDn7
ng_kq0pfY
ng_KQvHSt
ng_ks1NiL
ng_LFUEoA
ng_lGKev9
ng_LspLzg
ng_lX5XU5
ng_MAgtOU
ng_MqgHOb
ng_mTo25J
ng_mYnHYQ
ng_ngNbA9
ng_nIJI3E
ng_nJzItc
ng_NP4c3Q
ng_NyCGL9
ng_oaxB05
ng_OfMaoA
ng_oIha1j
ng_OmeFlJ
ng_owr4mr
ng_p2JJ7p
ng_P6ukhi
ng_p61VL3
ng_qDYSIy
ng_qh1y2V
ng_QJauYU
ng_qOIPoV
ng_qrPvFV
ng_QvvIqM
ng_qXYpzo
ng_QYpAVg
ng_rHGvU5
ng_rP2r2M
ng_RQNiJQ
ng_RUXo53
ng_Rzg2yB
ng_S9Dgmk
ng_sbIRn6
ng_sh3WZE
ng_SiJqLd
ng_SOjqis
ng_swDFmS
ng_sx14W6
ng_t60yvD
ng_TOvuIT
ng_tpjt5u
ng_TpY0z0
ng_TypsOu
ng_tzSE0G
ng_U8NkI3
ng_UfWZxY
ng_UnWQ47
ng_uO0ynC
ng_uRmghE
ng_VkD6ct
ng_vKOnYn
ng_vLmImy
ng_Vo3Hd3
ng_wEVR8A
ng_wfREKD
ng_WhnOKF
ng_wKluMS
ng_wko1Rf
ng_xAHrAG
ng_XdNnbS
ng_xjxaUr
ng_xNAKW6
ng_y4z1cr
ng_y7BK4p
ng_YaDSmQ
ng_Ydw0mV
ng_YEU4pZ
ng_yjyAJO
ng_yMNPS8
ng_yuFMtl
ng_YVUSLY
ng_YVxeoi
ng_Yw0y8Y
ng_ZTSyLH
ng_zYCV3z
...
```

**Comment by jabby** [comment] 2020-01-24 17:20
Hello @nimo23 

I just started to investigate your problem. I will try to summarize all problems and solutions.

* There is multiple log files under `/Users/workspace/ide/.metadata/` folder
  * Problem comes from the launch of angular language server: see https://github.com/eclipse/wildwebdeveloper/blob/8fb84afcc8a3e9d34db601ab8af5470b912cd3ac/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularLanguageServer.java#L40-L41
  * I think we should not use a timestamp in the log file name. 
  * We should verify preferences about logging angular language server. If I understand correctly the documentation of `Angular Language Service`, logging is disabled if there is no log file. 
* Angular Language Server is launch in debug mode
  * Obviously this line is the one to modify. https://github.com/eclipse/wildwebdeveloper/blob/8fb84afcc8a3e9d34db601ab8af5470b912cd3ac/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularLanguageServer.java#L53
* Angular language server use less efficient polling watcher
  * Accordingly to the implementation of the log, we should add an environment variable named `TSC_NONPOLLING_WATCHER` with value to `true`. See https://github.com/angular/vscode-ng-language-service/blob/master/server/src/server.ts#L50-L52
  * I don't know what is the impact of doing this modification. I will not modify this for the moment.
* Angular language server should not be launch when the project is not an angular project
  * I think we should create another issue for this point
* There are multiple folders with log files under `eclipse.app->Contents/MacOs`
  * I can't reproduce because I haven't an Apple laptop. I hope my following patch will help. 

Now I will work on the codebase in order to provide a patch about log files.

**Comment by jabby** [comment] 2020-01-24 17:56
I continue to investigate and I think there is a duplicate configuration to support angular. 

I just realized there is this configuration. https://github.com/eclipse/wildwebdeveloper/blob/8fb84afcc8a3e9d34db601ab8af5470b912cd3ac/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/jsts/JSTSLanguageServer.java#L52

@mickaelistria Do you know if it's mandatory to support angular into WWD?

**Comment by jabby** [comment] 2020-01-25 09:24
I created a first patch about this issue. It should fix the following problem.

* There is multiple log files under /Users/workspace/ide/.metadata/ folder 
  * With the patch, we use file only if logToFile is enabled. I also remove the timestamp in filename.

I will continue to work on the following items.

* Angular Language Server is launch in debug mode 

As I said, the problem comes from https://github.com/eclipse/wildwebdeveloper/blob/8fb84afcc8a3e9d34db601ab8af5470b912cd3ac/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/angular/AngularLanguageServer.java#L53

But there is more. If I set the value to `false`, Angular Language Service is also in debug mode (at least, there is the message in console). I checked into the code of vscode-ng-language-service and I found a bug. 
Accordingly to the nodejs documentation, all env variables are String. So when the language service check the value of `NG_DEBUG`, it should test if the variable is `'true'` or `'false'`. I will rise an issue about this.

```js
if (process.env.NG_DEBUG) { // does not work as expected because of the falsy / truthy values in JS
  session.info('Angular Language Service is running under DEBUG mode');
}
if (process.env.TSC_NONPOLLING_WATCHER !== 'true') { // works as expected
  session.warn(`Using less efficient polling watcher. Set TSC_NONPOLLING_WATCHER to true.`);
}
``` 

* Angular language server use less efficient polling watcher 

In client extension of vscode-ng-language-service, the `TSC_NONPOLLING_WATCHER` is always set to `'true'`. I will create a new patch and set `TSC_NONPOLLING_WATCHER` to true.

**Comment by jabby** [comment] 2020-01-25 09:47
Here is the issue about NG_DEBUG https://github.com/angular/vscode-ng-language-service/issues/579

**Comment by mickaelistria** [comment] 2020-01-28 16:22
@jabby I think this can now be marked as resolved thanks to your patch. Is there anything left to do? If not, feel free to close this issue.

**Comment by jabby** [comment] 2020-01-28 17:06
I think we can close this. 
@mickaelistria Do you know when a new release of WWD is scheduled?

**Closed by jabby** 2020-01-28 17:06 UTC

**Comment by mickaelistria** [comment] 2020-01-28 17:08
We can release Wild Web Developer any time. Last release was last week.
Is there any change you think is worth releasing soon?
